pxr/imaging/plugin/hdRpr/python/rpr.py
pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.h
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h

Fix incorrect preferences file path generation

Fix: Incorrect preferences file path generation

---

cmake/modules/FindRpr.cmake
pxr/imaging/plugin/hdRpr/CMakeLists.txt

Add RPR libraries to installation target

---

pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h

Fix: Incorrect primvar indexing #24

---

pxr/imaging/plugin/hdRpr/mesh.cpp

Fix: remove explicit 'pxr::' namespace usage

---

pxr/imaging/plugin/hdRpr/CMakeLists.txt
pxr/imaging/plugin/hdRpr/imageCache.cpp
pxr/imaging/plugin/hdRpr/imageCache.h
pxr/imaging/plugin/hdRpr/materialFactory.cpp
pxr/imaging/plugin/hdRpr/materialFactory.h
pxr/imaging/plugin/hdRpr/rprApi.cpp

* Minimize material memory usage
* Speed up material load time

Add simple image cache

---

pxr/imaging/plugin/hdRpr/materialAdapter.cpp

In the case when the same texture used for two relationships, the second one was ignored.
For example, we have UsdUvTexture referencing png with transparency. In that case, at the same time this one texture may be used as diffuseColor with `rgb` inputName and as opacity map with `a` inputName. Previously, opacity relationship was ignored.
So now we simply iterate over relationships instead of iterating over nodes.

Fix querying of UsdPreviewSurface textures

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

I missed to include those changes in #108 PR

Add missing methods after #108 PR

---

pxr/imaging/plugin/hdRpr/imageCache.cpp

Firstly test if image file format supported by USD and only then try to load the image using it

Avoid getting USD error while loading .rat image

---

pxr/imaging/plugin/hdRpr/materialFactory.cpp

As RadeonPro Render docs state, the emissive component blocks out all other layers. So to correctly render materials that have emissive parts we should set the emissive weight to 1.0 only for those parts that have non-zero emissive color

Fix emissive weight usage

---

pxr/imaging/plugin/hdRpr/materialFactory.cpp

All material nodes must be added to materialNodes list to get released when a material is freed

Fix memory leak

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp

When an interactive mode is requested, set max ray depth value to the interactive one.

Introduce basic interactivity support

---

pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.h
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h

Export render stats: percentDone, numCompletedSamples

---

pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h

Update mesh material if it was changed

---

pxr/imaging/plugin/hdRpr/imageCache.cpp
pxr/imaging/plugin/hdRpr/imageCache.h
pxr/imaging/plugin/hdRpr/materialFactory.cpp
pxr/imaging/plugin/hdRpr/rprApi.cpp

Implement image cache invalidation

---

pxr/imaging/plugin/hdRpr/distantLight.cpp
pxr/imaging/plugin/hdRpr/domeLight.cpp
pxr/imaging/plugin/hdRpr/domeLight.h
pxr/imaging/plugin/hdRpr/lightBase.cpp
pxr/imaging/plugin/hdRpr/renderParam.h
pxr/imaging/plugin/hdRpr/rprApi.cpp

- Implicit light will be removed if the user adds light later
- After user removes all lights from scene implicit light will be added

Fix implicit light creation behavior

---

pxr/imaging/plugin/hdRpr/materialAdapter.cpp
pxr/imaging/plugin/hdRpr/materialAdapter.h
pxr/imaging/plugin/hdRpr/materialFactory.cpp

Fix UsdUvTexture's scale and bias usage

---

pxr/imaging/plugin/hdRpr/lightBase.cpp
pxr/imaging/plugin/hdRpr/material.cpp
pxr/imaging/plugin/hdRpr/materialAdapter.h
pxr/imaging/plugin/hdRpr/materialFactory.cpp
pxr/imaging/plugin/hdRpr/materialFactory.h
pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h
pxr/imaging/plugin/hdRpr/volume.cpp

Add support of:
* Doublesided
* HdDisplayStyle::displacementEnabled

Improve mesh attributes support

---

pxr/imaging/plugin/hdRpr/package/CMakeLists.txt
pxr/imaging/plugin/hdRpr/package/install.py

Use RPR_SDK_PLATFORM as a package system identifier

Distinguish Centos and Ubuntu packages

---

pxr/imaging/plugin/hdRpr/package/install.py

* Search only for Houdini 18
* Improve UX: allow cancelation of install on "choose one of the Houdini install dirs" stage

Installer tweaks

---

pxr/imaging/plugin/hdRpr/materialFactory.cpp

Due to logical error, front face material was never set

Fix incorrect handling of doublesided attribute

---

pxr/imaging/plugin/hdRpr/materialAdapter.cpp
pxr/imaging/plugin/hdRpr/materialAdapter.h
pxr/imaging/plugin/hdRpr/materialFactory.cpp

Nested UsdTransform2d nodes are not supported. Such functionality requires much more time and would be better to implement when we will move to some more sophisticated material system
Resolves #188

Implement limited support of UsdTransform2d node

---

pxr/imaging/plugin/hdRpr/domeLight.cpp

In Houdini 18.0.287 we needed to invert X-axis of dome light to match with Karma, but in Houdini 18.0.311 this behavior is changed so now we need to invert Z-axis.
I made it so default behavior would be to match with Houdini 18.0.287, but for users of Houdini 18.0.311+ we will expose the ability to change this behavior by setting an environment variable

Add env setting to select dome light orientation

---

pxr/imaging/plugin/hdRpr/materialFactory.cpp

Previously, while we create material, not all places where RPR call could fail has been checked

Improve material creation error checking

---

pxr/imaging/plugin/hdRpr/mesh.cpp

Hybrid has slightly different behavior with instances and materials on them.
We need to set mesh material before creating any instances

Fix mesh instance material in Hybrid

---

pxr/imaging/plugin/hdRpr/rprApiAov.cpp

Fix denoise filter removal

---

cmake/modules/FindRif.cmake
pxr/imaging/plugin/hdRpr/CMakeLists.txt

AI denoiser does not work without these libraries

Include RIF dependency libraries to hdRpr package

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

* Correctly clear AOVs when switching between hybrid qualities
* Do not clear AOVs when switching into the state that requires a restart

Fix render quality switching

---

README.md
pxr/imaging/plugin/hdRpr/distantLight.cpp
pxr/imaging/plugin/hdRpr/renderThread.cpp
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h

We are interested in such fixes of this release:
FIR-1579 - DirectionalLightSetShadowSoftness should not take a coeff but an angle
FIR-1614 - Opacity > 1 on refractive materials
FIR-1595 - visibility flags not working on Curves
FIR-1588 - rprContextAbortRender aborts next rprContextRender
Resolves #210

Update to RPR SDK 1.34.7

---

pxr/imaging/plugin/hdRpr/CMakeLists.txt
pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
pxr/imaging/plugin/hdRpr/rprApi.cpp

Avoid skewing of 'Restart required' image

---

pxr/imaging/plugin/hdRpr/package/install.py

* When no install directories have been found ask the user for custom path
* If any installation directories have been found let the user ability to enter a custom path
* Do not query installation agreement when it's not necessary:
- when user selected install dir from the list
- when the user entered a custom path

Improve installation UX

---

pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.cpp

One of the applications of computed points is UsdSkel

Add support for computed points

---

pxr/imaging/plugin/hdRpr/mesh.cpp

Reuse the same vertex instead of copying whenever it's referenced by face

Fix subdivision mesh in case of geomSubset

---

pxr/imaging/plugin/hdRpr/instancer.cpp

* Support all meaningful types for `instanceTransform`, `translate`, `rotate` and `scale` primvars
* Sample only those transforms referenced in instanceIndices
* Minimize the number of allocations

Fix and optimize instancer's transform sampling

---

pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/volume.cpp

Transformation of the HdVolume primitive was not applied to hetero volume

Fix volume transform

---

pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py

* Control parameters should follow the "hidden" status of the controlled parameter

Fix Houdini RenderSettings UI

---

CMakeLists.txt
cmake/defaults/Options.cmake
cmake/defaults/Packages.cmake
pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.h
pxr/imaging/plugin/hdRpr/renderParam.h
pxr/imaging/plugin/hdRpr/renderPass.cpp

With backward compatibility to the previous USD version.
The main change: allow linkage against python3.

Update to USD 20.05

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

The main motivation here is to stick to one mutex everywhere we use `rpr::Context`.
Previously `rpr::Context` was not used anywhere except hdRpr so it was not the issue but now we need to sync RPR API access in [RprInteropTask](https://github.com/Radeon-Pro/RPRViewer/pull/5#discussion_r433676039)

Use rpr::Context's mutex to sync access to RPR API

---

pxr/imaging/plugin/hdRpr/basisCurves.cpp

I was profiling RPR on the scene with a quite huge curve primitive and noticed that most of the basis curves creation time was spent in std::vector::reserve function.
A straightforward solution for this issue is to precalculate the amount of required memory before converting Hydra data to RPR data.
Before these changes, basisCurves creation time was 9057.5ms, after - 107.0ms.

Speed up basis curves creation

---

pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp

Normals should be in [0; 1] range

Fix normal input of AI denoise filter

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

Account for high dependency of Northstar performance on RPR_CONTEXT_ITERATIONS: higher value gives better performance.

Add northstar specific rendering loop

---

CHANGELOG.MD
cmake/defaults/Version.cmake

In draft until CIS updates Houdini to the latest production release

1.3.0 Release

---

pxr/imaging/plugin/hdRpr/CMakeLists.txt
pxr/imaging/plugin/hdRpr/baseRprim.h
pxr/imaging/plugin/hdRpr/basisCurves.cpp
pxr/imaging/plugin/hdRpr/basisCurves.h
pxr/imaging/plugin/hdRpr/material.cpp
pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h
pxr/imaging/plugin/hdRpr/renderParam.cpp
pxr/imaging/plugin/hdRpr/renderParam.h

Mark rprim as dirty when their material is changed

---

pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h

Fix visibility sync for mesh instances

---

pxr/imaging/plugin/hdRpr/mesh.cpp

These changes are a follow up of this https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/330.
#330 PR tracks only the main material binding but it misses materials from geomSubsets because it's a specific thing of mesh primitive.

Mark mesh as dirty when geomSubset's material is changed

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

This PR https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/327 introduced a new render abort logic that was intended to avoid potential crashes when we abort the first rprContextRender call (when scene sync happens). Obviously, now we wait for a whole first sample to finish before aborting render. It leads to poor interactivity when moving the camera.
Changes in this PR try to fully mitigate this limitation while saving the logic that forbids aborts when Northstar syncs the scene.
Here how it works without these changes - https://youtu.be/2HaqVKEu7Sc, with these changes - https://youtu.be/bFkP-6iMBgk

Improve Northstar interactivity

---

pxr/imaging/plugin/hdRpr/volume.cpp

Fix a crash on getting volume data from the sceneDelegate

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

Revert y flip on rprsExport

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp

* Update API usage for setting motion transform
* Add support for RPR_CONTEXT_BEAUTY_MOTION_BLUR

Update motion blur for Northstar

---

pxr/imaging/plugin/hdRpr/domeLight.cpp

Revert #199

---

pxr/imaging/plugin/hdRpr/package/CMakeLists.txt
pxr/imaging/plugin/hdRpr/rprApi.h

Include python version in houdini package name

Update package script

---

deps/rprMtlxLoader/rprMtlxLoader.cpp
deps/rprMtlxLoader/rprMtlxLoader.h

Improve MaterialX loader
* Added support of MaterialX distance and angle units
* Added support of MaterialX non-LUT colorspaces
* Implementation for colorspace conversions taken from MaterialX stdlib glsl code.

Improve MaterialX loader

---

README.md

Performance optimization for zen2+ and bulldozer arch.
nothing.
nothing.
Someone may display a warning that this optimization does not work on Haswell, IvyBridge and Intel (R) archs before GerminiLake.

improve performance for multicore and multithread (SMT) CPUs

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

Update RPR to v2.1.9
Added support of adaptive sampling for Northstar

Update RPR to v2.1.9

---

pxr/imaging/plugin/hdRpr/baseRprim.h
pxr/imaging/plugin/hdRpr/basisCurves.cpp
pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h

Hotfix compilation errors from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/443

Fix compilation error

---

deps/rprMtlxLoader/rprMtlxLoader.cpp
deps/rprMtlxLoader/rprMtlxLoader.h
pxr/imaging/rprUsd/materialRegistry.cpp

Resolve https://amdrender.atlassian.net/browse/RPRVIEW-175
* Added support of MaterialX tangent geomprop
* Improved MaterialX loader logging - more granular control over logging verbosity.

Mtlx: support tangent geomprop, improve logging

---

pxr/imaging/plugin/hdRpr/distantLight.cpp
pxr/imaging/plugin/hdRpr/domeLight.cpp
pxr/imaging/plugin/hdRpr/light.cpp

To fix RPRVIEW-218
Fixed distant light visibility tracking.

Fix distant light visibility

---

deps/rprMtlxLoader/rprMtlxLoader.cpp

To fix crash when using standard_surface material.
None, changes that lead to this behavior were not released.
Re-use already created a constant texture node instead of re-creating it.

RPRMaterialXLoader: fix passthrough node

---

pxr/imaging/plugin/hdRpr/mesh.cpp

To add support of deformation blur of computed geometry.
Added support of deformation motion blur of computed geometry in the Full quality.
Use the new API introduced in USD 21.05 (https://github.com/PixarAnimationStudios/USD/pull/1455) to sample a user-controlled amount of `points` samples of computed geometry.
This feature is working in USD 21.05+ only.

Add support of deformation blur for computed geometry (UsdSkel)

---

pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp

To improve toon shader
* Added color parameter to the toon shader node:
- renamed shadow/mid/highlight colors to shadow/mid/highlight tints
- added color parameter to which tints are applied
* Fixed default normals on the toon shader

Tweak toon shader

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp

Add support for new RPR contour algorithm
Updated contour rendering
Updated generator of render settings
Added required UV_AOV
Added new context parameters
Do we need to expose all new settings to users?

Contour rendering update

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.h
pxr/imaging/rprUsd/schema.usda

Added simple gamma filter, in case if tonemap gamma is too complex
Added simple gamma filter
- Added gamma into the schema and render settings generator
- Fixed hidewhen on some properties
Notes, if needed.

Simple gamma filter

---

pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp

Updated toon shader
Added 5 colors mode and transparency logic
Added new toon inputs from RPR SDK
Added runtime creation of transparent and blend nodes (require storing rpr context inside node)
Notes, if needed.

Toon shader update

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py

To fix Houdini UI for contour render settings.
Contour render settings are correctly shown when the Contour render mode is enabled.
Fixed hidewhen condition.

Fix contour render settings

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py

Fix Houdini .ds generation for render settings
Fixed Houdini render settings node parameters visibility.
Preprocess all hidewhen conditions in the same way as for settings. Fix hidewhen conditions for contour and cryptomatte settings.
Should have been a part of [#525](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/525) but it was merged faster than the blink of an eye.

Fix Houdini .ds generation for render settings

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Flip vertical wasn't presented in schema and wasn't working
Fixed flipVertical render settings
Updated schema.usda
Notes, if needed.

Updated flip vertical schema

---

pxr/imaging/plugin/rprHoudini/houdiniPluginActivator.cpp.in

Houdini activator does not work on some windows machines
Houdini activator now can find more potentially viable implicit HOUDINI_USER_PREF_DIR values.
Check an additional viable location of implicit HOUDINI_USER_PREF_DIR

Improve houdini activator

---

CMakeLists.txt

Update minimum cmake version required for build
Updated minimum cmake version required for build
Updated  cmake_minimum_required

Up minimum cmake version

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

Add support for missing HybridPro depth ray settings.
Added support for HybridPro depth ray settings.
- Added check for pluginType;
- added setting corresponded settings.

BLEN-8: [HdRPR] Refraction not working correct

---

cmake/defaults/Options.cmake
cmake/defaults/gccclangshareddefaults.cmake
cmake/defaults/msvcdefaults.cmake
cmake/macros/Private.cmake
cmake/modules/FindOpenEXR.cmake
pxr/imaging/plugin/hdRpr/camera.cpp
pxr/imaging/plugin/hdRpr/material.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.h
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/CMakeLists.txt
pxr/imaging/rprUsd/materialNodes/houdiniPrincipledShaderNode.cpp
pxr/imaging/rprUsd/materialNodes/mtlxNode.cpp
pxr/imaging/rprUsd/materialNodes/rpr/combineShadersNode.cpp
pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
pxr/imaging/rprUsd/materialNodes/rpr/nodeInfo.h
pxr/imaging/rprUsd/materialNodes/usdNode.cpp
pxr/imaging/rprUsd/materialRegistry.cpp
pxr/imaging/rprUsd/materialRegistry.h

Hi! I recently updated RprUSD to USD 22.05 to test it with the latest USD MaterialX changes.
Please let me know your stance on merging this.
Known issues:
- dome light is upside down
- camera light is too bright

Update to USD v22.05

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Update RPR SDK to 2.2.15
Updated RPR SDK to 2.2.15
Update RPR SDK to 2.2.15
Fix typo RPR_CONTEXT_RAY_CAST_EPISLON -> RPR_CONTEXT_RAY_CAST_EPSILON

Update HdRPR with core 2.2.15

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

resolves https://amdrender.atlassian.net/browse/RPRHOUD-16

progress percentage fix

---

pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.h

Depth AOV displays incorrect information. Background values are 0.5, but correct value is 1.
Now depth AOV provides correct depth data
A new filter has been added to depth AOV. It fixes bug with background value

Depth AOV background fix

---

INSTALL.md
pxr/imaging/plugin/hdRpr/CMakeLists.txt
pxr/imaging/plugin/hdRpr/scripts/rendersettings_OnLoaded.py
pxr/imaging/plugin/rprHoudini/houdiniPluginActivator.cpp.in

replace rendersettings nodes with old settings format to new ones
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-12, https://amdrender.atlassian.net/browse/RPRHOUD-10
implemented a script to replace rendersettings nodes with new ones (with new settings format) copying existing settings into it

Render settings autoupdate

---

pxr/imaging/plugin/hdRpr/rprApi.cpp

Fix for https://amdrender.atlassian.net/browse/RPRHOUD-13
Implemented by temporarily moving the camera
Still doesn't work correctly for the orthographic camera, created issue https://amdrender.atlassian.net/browse/RPRHOUD-32

Tiling render implementation

---

cmake/modules/FindOpenEXR.cmake

Revert unnecessary changes in cmake file to fix plugin build on macos

macos build fix

---

pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h

Added rendering time output to use in autotests

profile output

---

pxr/imaging/plugin/hdRpr/CMakeLists.txt

fixing the build issue in HDRPR that appear after .rat file conversion PR merge

include path fix

---

pxr/imaging/plugin/hdRpr/rendererPlugin.h

USD v23.02 is incompatible with current version of our plugin
This RP changes signature of HdRprPlugin::IsSupported method to be compatible with latest USD

Update to USD 23.02

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

RPR random seed parameter needs to be exposed
This PR add RPR random seed parameter to render delegate

Random seed setting

---

pxr/imaging/rprUsd/lightRegistry.cpp

Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-62

toon lighting fix

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Release 28.04.23

---

cmake/modules/FindOpenEXR.cmake

Attempt to fix hdRPR build on linux (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/621)

exr module update

---

pxr/imaging/plugin/hdRpr/light.cpp
pxr/imaging/plugin/hdRpr/python/generateLightSettingFiles.py
pxr/imaging/rprUsd/schema.usda

PR fixes https://amdrender.atlassian.net/browse/RPRHOUD-21
Now lights have additional parameter to tune light intensity

Light intensity multiplier

---

pxr/imaging/plugin/hdRpr/mesh.cpp
pxr/imaging/plugin/hdRpr/mesh.h
pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py

Resolves https://amdrender.atlassian.net/browse/RPRHOUD-55 (subdivision level)

subdivision scheme setting

---

pxr/imaging/rprUsd/CMakeLists.txt

Resolves https://amdrender.atlassian.net/browse/RPRUS-167

fix for build with relative path

---

pxr/imaging/plugin/rprHoudini/scripts/python/houRpr/materialLibrary.py

Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-69
When the material is imported, the script parses the MaterialX file and generates a graph of MaterialX nodes related to the material.
A graph is placed into the newly created library when the material is imported on a state level, or into a subnet when imported on the library/subnet level.
Also added sorting for material/category lists and hashing for the faster import window opening.

mtlx editing

---

pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h
pxr/imaging/plugin/hdRpr/volume.cpp
pxr/imaging/plugin/hdRpr/volume.h

This PR enables processing of volume visibility flag

Volume visibility

---

pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp

Resolves https://amdrender.atlassian.net/browse/RPRHOUD-91
In the toon shader, only scalar transparency was supported. Added support to connect nodes as inputs as well.

Transparency map support for toon shader

---

pxr/imaging/plugin/hdRpr/aovDescriptor.cpp

Resolves https://amdrender.atlassian.net/browse/RPRUS-172

HdFormatInvalid format assignment for invalid descriptor

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Resolves https://amdrender.atlassian.net/browse/RPRHOUD-96

filter type selection

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/rprUsd/schema.usda

Implements https://amdrender.atlassian.net/browse/RPRHOUD-66

sampling defaults update

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Add a setting to enable GMON

---

pxr/imaging/rprUsd/contextHelpers.cpp

1 MB buffers allocations for Hybrid in GetGpuName

1 MB buffers allocations for Hybrid in GetGpuName

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/rprUsd/schema.usda

Add reservoir sampling setting

Add reservoir sampling setting

---

CMakeLists.txt
pxr/imaging/plugin/hdRpr/CMakeLists.txt
pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/renderBuffer.cpp
pxr/imaging/plugin/hdRpr/renderDelegate.cpp
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApi.h
pxr/imaging/rprUsd/contextHelpers.cpp
pxr/imaging/rprUsd/contextMetadata.h
pxr/imaging/rprUsd/schema.usda

Add interop

---

pxr/imaging/rprUsd/hdMtlxFixed.cpp

Add support for nodes with `multioutput` type
Added support for nodes with `multioutput` type

Add support for multioutput nodes

---

pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
pxr/imaging/plugin/hdRpr/rprApi.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.cpp
pxr/imaging/plugin/hdRpr/rprApiAov.h

Resolves: https://amdrender.atlassian.net/browse/RPRUS-175
Denoising and upscaling with RIF removed
UI updated to support Hybrid denoising and upscaling

removed rif denoising and upscaling

---

pxr/imaging/rprUsd/materialRegistry.cpp

Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-28

macos mtlx path fix

---

pxr/imaging/plugin/hdRpr/primvarUtil.h

Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-108

primvar extraction for multiple timestamps fix

---

pxr/imaging/plugin/hdRpr/points.cpp
pxr/imaging/plugin/hdRpr/points.h

Instaicing can't be applied to points (https://amdrender.atlassian.net/browse/RPRHOUD-109)
For now instancing is implemented

Add instancing for points

---

cmake/defaults/Version.cmake

Update the version from 3.0.2 to 3.0.3

version update to 3.0.3

---

cmake/defaults/Version.cmake

Update the plugin version to 3.0.4.

Version update to 3.0.4.
