- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
I changed this line in ~/workspace/pkgs/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/materialAdapter.cpp :
```
else if (paramName == HdRprTokens->normal)
{
m_texRprx.insert({ RPRX_UBER_MATERIAL_NORMAL, materialTexture });
}
```
with this:
```
else if (paramName == HdRprTokens->normal)
{
m_texRprx.insert({ RPRX_UBER_MATERIAL_DIFFUSE_NORMAL, materialTexture });
m_texRprx.insert({ RPRX_UBER_MATERIAL_REFLECTION_NORMAL, materialTexture });
}
```
> uber_normal_material lines changes

- README.md
- pxr/imaging/plugin/hdRpr/domeLight.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Hello,
Dome lights currently do not respect the authored transform of the light in the USD stage.
This PR gets the transform from the sceneDelegate and adds it to the rprEnvironmentLight, along with defining a new token for the HDRprDomeLight.
Tested locally against USD 18.09.
Thank you,
-Colin
> Add transform to dome light

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Fix for GCC 4.8.5 - version shipped with CentOS 7.6. 
* Problem in rprApi.cpp:352
Solution: Apply a coding convention for structure variables as in ImageFilter.h:RifParam
> Fix: GCC 4.8.5 compilation error

- cmake/modules/FindRif.cmake
- cmake/modules/FindUSD.cmake
- pxr/imaging/plugin/hdRpr/CMakeLists.txt
Allow user to use monolithic USD
> Fix: CMake workaround for monolithic USD build

- pxr/imaging/plugin/hdRpr/python/rpr.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
GUI render device switching button actually does not really change device type but simply update HdRprPreferences. To really change render device we should somehow reset current context and refill scene. Unfortunately, USD API does not provide the possibility to do some sort of hot reset of renderer plugin, like usdViewApi.RestartPlugin()
I propose shortest in time workaround for this problem but obviously not the most optimal one.
> Fix: Broken render device switching

- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialFactory.cpp
In the case of USDZ, stage textures referenced by materials could be embedded into the stage file which is a zip archive.
If the path to the stage is "/scene.usdz" and "0/image.png" is an asset path referenced from some material then resolved path would be "/scene.usdz[0/image.png]" which definitely not supported by rprContextCreateImageFromFile
So the best solution is to use USD API for loading images because such cases would be handled automatically. Also will be supported all image formats that USD supports, i.e. imaging plugins, such as opeimageio, will automatically expand the list of supported image formats
> Fix: Loading of textures of materials from USDZ

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
When OpenGL context is not set correctly 'glewInit' eventually will fail with error 'Missing GL version'. In case of that, the fallback path will be used, i.e. without GL interoperability.
The proposed changes make it possible to easily add GL interoperability checkbox to usdview GUI.
> Fix: Dynamically derive if GL interoperability can be used

- README.md
- pxr/imaging/plugin/hdRpr/python/rpr.py
'memory_maps' was removed on macOS in psutil v5.6.0
Using USD API to resolve RPR library path we can remove psutil from required dependencies and eliminate the problem caused by missing 'memory_maps' on macOS
> Resolve RPR library path using USD Plugin API

- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialFactory.cpp
...because this may be configured to be something other than default. either
rely on PXR_NAMESPACE_OPEN_SCOPE, or use PXR_NS::
> don't explicitly use the pxr:: namespace

- pxr/imaging/plugin/hdRpr/sphereLight.cpp
were two issues:
1. it didn't take the radius into account
2. the formula for surface area was wrong the "3/" should have been inside
the outermost pow, not outside
> fix sphereLight normalization

- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
...was getting warnings about them with gcc-6.3.1, but probably good to tidy up regardless
> remove some unused vars

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/mesh.cpp
While attempts to get, ie, "primvars:st:indices" directly will work (after printing ominous
errors), it should be avoided because the results returned from Get and SamplePrimvar are
already flattened - and re-indexing will give incorrect results.
Also, even if it did work, the fact that indices may be stored at "primvars:st:indices" is
an implementation detail of the UsdImaging scene delegates - other scene delegates could
behave differently.
This resolves the issues discussed here:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/34#issuecomment-513005738
> avoid attempting to get primvar indices directly

- pxr/imaging/plugin/hdRpr/sphereLight.cpp
Adds the optimization discussed here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/38#discussion_r305449996
...as well as other small tweaks
- use simpler formula for surface area of sphere if possible
- calculate the various sx^p only once (not twice each)
- add checks to avoid division by zero
> optimize HdRprSphereLight::NormalizeLightColor

- cmake/modules/FindRpr.cmake
- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/basisCurves.h
- pxr/imaging/plugin/hdRpr/domeLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.h
- pxr/imaging/plugin/hdRpr/field.cpp
- pxr/imaging/plugin/hdRpr/field.h
- pxr/imaging/plugin/hdRpr/lightBase.cpp
- pxr/imaging/plugin/hdRpr/lightBase.h
- pxr/imaging/plugin/hdRpr/material.cpp
- pxr/imaging/plugin/hdRpr/material.h
- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialAdapter.h
- pxr/imaging/plugin/hdRpr/materialFactory.cpp
- pxr/imaging/plugin/hdRpr/materialFactory.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/rectLight.cpp
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/renderPass.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/sphereLight.cpp
- pxr/imaging/plugin/hdRpr/volume.cpp
- pxr/imaging/plugin/hdRpr/volume.h
- Remove RPRX material system usage, use plain RPR material system instead.
- Fix numerous memory leaks due to missing 'DeleteMaterial' calls.
- Force cmake to search RPR libraries only in RPR_LOCATION_LIB
> Refactoring: Use new RPR (1.34.1) material system

- pxr/imaging/plugin/hdRpr/mesh.cpp
When original mesh has no normals or uvs submesh does not have it either
> Fix GeomSubset mesh splitting

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
* Plugins should not expose any headers with implementation details
> Remove any headers from the public interface

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprcpp/rprContext.cpp
GlfGlewInit is a thread safe wrapper around glewInit and it guarantees that glewInit will be called once
> Call GlfGlewInit instead of glewInit

- pxr/imaging/plugin/hdRpr/instancer.cpp
- pxr/imaging/plugin/hdRpr/instancer.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Every time instancer was dirty new instance for each transform was created but previously created instances have been never released
I have fixed it in such a way that HdRprMesh now always store the required number of instances and whenever instancer is dirty it updates transform for each instance, i.e. without instance release
Regarding the visibility attribute - it was not used at all
> Fix varying instancer and mesh visibility attribute

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
Link only to tbb library instead of linking to all available tbb libraries
> Fix linkage against TBB library

- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderBuffer.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
When the user allocates HdRenderBuffer of a particular size and his viewport is of another size internal framebuffer that corresponds to HdRenderBuffer would be resized to the viewport size. It's inappropriate hidden behavior.
In perspective of the multithreaded application, it could cause the crash. And I was able to reproduce it.
Define the size of each AOV framebuffer separately removing global framebuffer size that existed before
In one thread you draw HdRenderBuffer to your viewport:
```
width = renderBuffer->GetWidth();
height = renderBuffer->GetHeight();
renderBuffer->Resolve();
data = renderBuffer->Map();
// Draw data
```
In another thread, you are executing renderPass.
Let's say you stretch the window and viewport size is getting smaller. And here is a key moment: when you draw …
> Remove global framebuffer size

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
It looks like previously RPR library had broken rpath and so was added this workaround. But now it's redundant due to correct rpath in RPR SDK and even more, it does not allow us to distribute build among users due to hardcoded install name of RPR library
> Fix hdRpr's install name of RPR library

- cmake/defaults/Packages.cmake
USD build has "boost" version lass than 1.65 on every platform.
Accordingly to cmake's FindBoost, the python component requires a Python version suffix only starting from Boost 1.67.
So as my main development machine currently is windows with MSVC 2019, I had to build USD against the latest Boost version that required version suffix for python component. My local change was accidentally leaked to one of PR. We need to rollback it
> Remove version suffix from python component in find_package

- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
This allows us to avoid receiving RIF warnings about dettaching of an unattached filter
> Track RIF filter attach status

- pxr/imaging/plugin/hdRpr/config.cpp
- pxr/imaging/plugin/hdRpr/config.h
- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderBuffer.h
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/renderPass.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
This checkin adds some sampling controls.  Namely min samples, max samples, and variance.
We set is_converged on the render buffer and the render pass based on the criteria
is samples > max samples or are all pixels converged to variance threshold.
Open TODOs:
How do we mark buffers and render pass as not converged and set iterations to 0 when changes happen?
How do we set defaults here?
Expose in Menu?
> Add sampling controls

- pxr/imaging/plugin/hdRpr/config.cpp
- pxr/imaging/plugin/hdRpr/config.h
- pxr/imaging/plugin/hdRpr/houdini/HdRprPlugin_Viewport.ds
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
* Mark buffers and render pass as not converged every time render pass is executed. We can do it because when render settings are changed HdRenderPass::_Execute is always called
* Set iterations to 0 when we clear our framebuffers
* Add sampling controls to Houdini UI
* Introduce UI toggle to enable or disable adaptive sampling
* Synchronize Hydra Render sampling settings with HdRprConfig
> Tweak sampling controls

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebuffer.cpp
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebuffer.h
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebufferGL.cpp
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebufferGL.h
The logic behind `HdRprRenderBuffer` resizes was broken for color AOV. `HdRprRenderBuffer` implements resizing in the manner of consecutive calls to `_Deallocate` and `_Allocate` with a new size, but currently, `_Deallocate` for color AOV does not work due to limitation in RPR API - color AOV must be always enabled
Fixes #94
> Fix color AOV resize

- pxr/imaging/plugin/hdRpr/rprApi.cpp
After the first hdRpr initialization, HdRprConfig's sampling attributes were marked as clean. But when you reinitialize hdRpr, HdRprConfig's sampling is no longer dirty that's why the number of max samples was never queried again until you set a new value for one of the sampling attributes in HdRprConfig. Thus the number of max samples was always 0. This behavior was mentioned in #95
> Fix iteration count initialization

- pxr/imaging/plugin/hdRpr/rprApi.cpp
This code, part of my debug code, accidentally leaked into hdRpr when I was implementing orthographic projection
> Fix camera sensor size for cases when height bigger than the width

- pxr/imaging/plugin/hdRpr/imageCache.cpp
This case was previously not added to this switch because of compilation error on macOS, but now this issue is resolved
> Fix support of half float textures

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Correctly process subdivision surfaces: do not query normal primvar for such meshes, even if it has authored normals, in such situations rely on information provided from primvarDescriptors. Never try to get primvar value if it's not available in primvarDescriptors.
Implement more robust `Sync` in case of targeted changes.
> Refactor HdRprMesh::Sync method

- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialFactory.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
* Fix translucent layer: `diffuse_weight = opacity` and `refraction_weight = 1 - opacity`
* Set fallback values for absent parameters
* Set refraction color to white
* Handle left-hand oriented meshes
> Material fixes

- pxr/imaging/plugin/hdRpr/rprApi.cpp
`HdRprApi::CreateCurve` was returning wittingly incorrect curve object because it was detached and released in the destructor of previously created RprApiObject from the same curve object rpr handle
> Fix crash on release of HdRprBasisCurve

- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/basisCurves.h
- pxr/imaging/plugin/hdRpr/rifcpp/rifContext.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifContext.h
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
RPR API does not have `rprCurveSetVisibility*` functions like for shapes, that's why visibility on/off emulated using scene attach/detach. It should be fixed in the future when RPR API will be updated.
I have already created an appropriate issue in the backlog - FIR-1575
> Implement basis curves visibility support

- pxr/imaging/plugin/hdRpr/instancer.cpp
- pxr/imaging/plugin/hdRpr/instancer.h
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
moral of history: never use uncheckedGet if you are not absolutely sure about the held type
> Fix instancer rotation and memory leak

- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderBuffer.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebuffer.cpp
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebuffer.h
* Avoid potential crashes due to incorrect usage of HdRenderBuffer API by external code. According to my observations, HdRenderBuffer might be reallocated while in a mapped state. Also, after reallocation HdRprRenderBuffer's internal buffer used to store resolved image has been in an incorrect state - it didn't match new width and height - until first Resolve call.
> Fix crash on resize of HdRprRenderBuffer

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
#121 introduced a slightly different API to query AOV size. #129 was not synced with those changes before merging
> Fix compilation error due to missyncronization within PRs

- pxr/imaging/plugin/hdRpr/rprApi.cpp
* Allow non-destructive updates for current render state:
- Enabling/disabling denoising
- Increasing number of max samples
> Reset iteration count only when required

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
In Houdini, it's possible that `HdRpRenderPass::_Execute` called multiple times while `HdRprApi::Update` was not finished yet, in such case render stop would be called because `HdRprConfig` is still dirty. Lock `HdRprConfig` instance before reading/writing  to avoid it
> Avoid false render stops

- pxr/imaging/plugin/hdRpr/rprApi.cpp
If viewport size is changed perspective camera should be updated accordingly to a new aspect ratio
> Update camera when viewport changed

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
- pxr/imaging/plugin/hdRpr/rifcpp/rifImage.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifImage.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
- Decouple AOV logic from **HdRprApi** to simplify its supporting
- Introduce internal and bound AOVs
- Bound AOV lifetime controlled by **HdRenderPassState** AOV binding list.
- Internal AOVs currently used only for denoising.
- Internal and bound AOV can point to the same underlying AOV, so we are not creating multiple AOV when AOV of the same type required as output and as input for denoising.
- The uniqueness of AOV controlled via aovRegistry.
- The specific logic of AOV type is encapsulated inside of AOV class
- **HdRprApiColorAov** contains denoise logic
- NDC Depth calculation from worldCoordinate AOV contained only in **HdRprApiDepthAov** class and also **HdRprApiDepthAov** retains worldCoordinate AOV so that it will exist until depth AOV released
- Numerous fixes of rif wrapper: …
> Improve RIF filters usage and AOV handling

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
Currently, it affects 'Render quality' UI controls on macOS
> Make Houdini UI param invisible when its category is disabled

- pxr/imaging/plugin/hdRpr/materialFactory.cpp
The same RPR object of `displacementMaterial` was released twice: explicitly via `SAFE_DELETE_RPR_OBJECT(material->displacementMaterial)` and when all retained material nodes (`RprApiMaterial::materialNodes`) were released later
Resolves #157
> Fix crash caused by over-release of displacement material node

- pxr/imaging/plugin/hdRpr/materialFactory.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
Displacement material relies on the mesh subdivision factor. Whenever the subdivision factor is 0 we need to unset displacement material and vice versa if the subdivision factor is greater than 0 we should set displacement material.
> Fix mesh displacement material setting

- pxr/imaging/plugin/hdRpr/rprApi.cpp
* Do not mark AOV registry as dirty if AOV is already in it
* When creating AOV that already exists, resize and change AOV format if needed
> Fix AOV binding logic

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
This very useful feature that allows getting important info from hdRpr users in case of any issues,
especially in Houdini where all USD errors go to console which could be inaccessible in case of crashes.
Currently, there is no such embedded functionality in USD
> Add ability to dump USD errors to a specified file

- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/basisCurves.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Resolves #154
As from plugin standpoint feature is ready to merge, but the current core has some issues:
* Copypaste from jira ticket FIR-1600:
> Artefacts on tapered curves render in GPU mode
> In general, tapered curves works fine in both GPU and CPU modes, but some of the curves have pronounced artefacts in GPU mode. First of all, it's not expected that they are so wavy, but that's not why I'm creating this bug. Have a look at rendered images when you changing the camera position a bit.
> While rendering with CPU there are no such artefacts, but curves are wavy anyway
[images.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/3927154/images.zip)
* Radius interpolation does not seem correct to me. For example, with such parameters of RPR curve:
``` …
```
> Implement support of tapered basis curves

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
Previously all render settings we had have been listed in "Display Options".
In such a way they were global for the whole project.
It obviously has its downsides such as inability to easily go from one render settings set to the other.
Using "Render settings" node you can easily automate this process.
Resolves #142
> Expose RPR render settings in Houdini's "Render settings" node

- pxr/imaging/plugin/hdRpr/materialFactory.cpp
This bug comes from #168. Due to logical error, the subdivision was enabled even for meshes without displacement material
> Remove undesirable implicit subdivision on non-displaced meshes

- pxr/imaging/plugin/hdRpr/rprApi.cpp
RPR API requires each indices array to be set, even if primvar indices are the same as point indices
> Fix mesh vertex interpolated primvars

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
Whenever AOV was bound before but its format is changed, the format was never updated
> Fix bound AOV format change

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/camera.cpp
- pxr/imaging/plugin/hdRpr/camera.h
- pxr/imaging/plugin/hdRpr/field.h
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/volume.h
Default Hydra Camera (**HdCamera**) does not support parameters defined in **UsdGeomCamera** such as:
* Aperture Size
* Focal Length
* FStop
* Focus Distance
* Shutter Open
* Shutter Close
* Clipping Range
To process these parameters custom **HdRprCamera** class that inherits **HdCamera** is introduced. This class simply adds syncing of missing parameters so that they could be used by the render engine.
Resolves #164
> Add support for camera parameters that HdCamera missing

- pxr/imaging/plugin/hdRpr/rifcpp/rifContext.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifImage.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
After [RIF-#330](https://github.com/Radeon-Pro/RadeonProImageProcessing/pull/330) row_pitch value is in bytes, previously it was in pixels.
Also, automatic row_pitch calculation has been introduced, i.e. when row_pitch is 0 RIF will calculate it by himself
This PR should be merged when we move to RIF 1.4.3+
> Fix RIF image creation

- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
- pxr/imaging/plugin/hdRpr/rprcpp/rprFramebuffer.cpp
Previously all pixels always had 1.0 alpha, now we combine alpha AOV with color AOV to produce an image which is ready for compositing with alpha pre-multiplied colors (as Hydra requires)
Before:
After:
> Add alpha-compositing support

- pxr/imaging/plugin/hdRpr/rprApi.cpp
After this [changes](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/170/files#diff-38c7659c001857a7912c3173c57433f0R1688-R1689),
```
std::memcpy(mappedData, textureData->GetRawBuffer(), imageDesc.image_slice_pitch);
```
had no effect because `imageDesc.image_slice_pitch` was zero
> Fix rendering of RestartRequired image

- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.cpp
- pxr/imaging/plugin/hdRpr/rifcpp/rifFilter.h
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
In CPU mode, we need to move RPR framebuffer data to RIF images explicitly. We were not doing it with the latest AOV changes
> Fix rendering in CPU mode

- pxr/imaging/plugin/hdRpr/rprApi.cpp
As Richard said:
> looks like there is an issue in the doc
the argument is not a normalized [0,1]
it's a simple time value
> Remove incorrect comment about camera exposure

- cmake/modules/FindRpr.cmake
- pxr/imaging/plugin/hdRpr/rprcpp/rprContext.cpp
For some reason, Hybrid library for UNIX systems does not have a "lib" prefix unlike Tahoe library, which is weird.
Fixing it on side of RadeonProRenderUSD is much easier than fixing it in RadeonProRenderThirdPartyComponents and all other plugins
> Fix Hybrid plugin registration on Ubuntu

- cmake/modules/FindRpr.cmake
This [change](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/commit/95ac0af97f2038e37f2ff126061a384e451d67fc) works on Ubuntu and CentOS, but does not work on macOS
> Fix building on macOS

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
It's already done in FindOpenVDB.cmake
> Remove redundant cmake code

- pxr/imaging/plugin/hdRpr/material.cpp
- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialAdapter.h
Because refractive material can not be single-sided
> Do not mark refractive materials as doublesided

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Previously, after invoking render delegate in broken state, the delegate would never reach a converged state even though it wouldn't actually be doing any rendering
> Mark bound AOVs as converged even in case of error

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Also, make medium quality single-sampled (just like Low quality)
I want to point out that medium quality still crashes GPU driver on Radeon VII but I've tested it on RTX 2060 SUPER and it works. So I think it would be better to remove this quality lock so that more users could try it
> Unlock medium quality

- pxr/imaging/plugin/hdRpr/rprcpp/rprContext.cpp
- pxr/imaging/plugin/hdRpr/rprcpp/rprContext.h
In back old days this behavior was pretty convenient, but right now it confusing.
For example, you have selected High quality, i.e. use Hybrid plugin, but in case Hybrid plugin can't be loaded for some reason Tahoe would be loaded automatically and there would be no sign of problem, of course except logged error message which Houdini tends to hide
> Remove brutforce search of the working one plugin when context with requested plugin is can't be created

- cmake/defaults/Options.cmake
- cmake/macros/Private.cmake
- cmake/macros/Public.cmake
- cmake/modules/FindUSD.cmake
- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
These changes keep compatibility with 19.11 but also provide support of 20.02
Summary of 19.11 to 20.02 changes that affect hdRpr:
* 20.02 renamed `linearDepth` to `cameraDepth` and changed depth range from [-1, 1] to [0, 1]. (https://github.com/PixarAnimationStudios/USD/commit/609ccf1cc59670443a56e682bbe4a0c2611fb8b4)
So I refactored usage of this token to support both 19.11 and 20.02 names and added additional remapping filter.
* In 20.02 library prefix on windows was fixed (https://github.com/PixarAnimationStudios/USD/commit/1ca7422061007fd7b91db7e68620cdd571dd8cb5s)
I've updated cmake files in accordance with the changes in USD repo. Now if the user compiled USD with custom library prefix he can feed the same prefix to hdRpr's cmake and it will link against correct libraries …
> Update to USD 20.02

- pxr/imaging/plugin/hdRpr/rprApi.cpp
* Tahoe requires that `AOV_VARIANCE` is created for adaptive sampling to work
* Set `RPR_CONTEXT_FRAMECOUNT` parameter to the current sample count (should not `RPR_CONTEXT_FRAMECOUNT` be named as `RPR_CONTEXT_SAMPLECOUNT`?)
> Fix adaptive sampling

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/notify/message.cpp
- pxr/imaging/plugin/hdRpr/notify/message.h
- pxr/imaging/plugin/hdRpr/notify/message.mm
- pxr/imaging/plugin/hdRpr/rprApi.cpp
Implement long-living Fianna's request - popup window when you have to restart renderer.
On windows, I use `MessageBox` from the Windows Forms library.
On macOS AppKit's `NSAlert`.
Linux is the hard one, there are no such system GUI APIs on Linux. The easiest way I've found is to use `xmessage`.
> Add "restart required" popup

- cmake/defaults/msvcdefaults.cmake
The reason why it compiles successfully for Houdini is that Houdini's cmake target adds this definition to our target in an implicit manner - you can find it in `$HFS/toolkit/cmake/HoudiniConfig.cmake`
> Fix compilation of usdview plugin on windows

- pxr/imaging/plugin/hdRpr/rendererPlugin.cpp
- pxr/imaging/plugin/hdRpr/rendererPlugin.h
It's used by Houdini's husk to pass all its render settings
> Add the factory method to create render delegate with initial settings

- pxr/imaging/plugin/hdRpr/light.cpp
Lights were working because `DirtyParams` equals 1 and Hydra creates light from scratch when it's changed. But `||` is obviously a typo
> Fix light transform sync

- pxr/imaging/plugin/hdRpr/light.cpp
The spotlight in RPR and Karma is fundamentally different. The former has hard shadows, the latter has soft shadows. Also, the RPR spotlight penumbra uses different attenuation function.
No way to match them, at least on the plugin side.
The motivation for the removal of an empirical multiplier is very big intensity on the scenes with a big number of spotlights (like [BarScene](https://www.sidefx.com/contentlibrary/bar-scene/) and [RenderMan's Solaris teapot demo](https://rmanwiki.pixar.com/display/RFH23/Solaris+Tutorial))
> Remove spotlight empirical intensity multiplier

- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
I've aliased Houdini's `frontface` to a more explicit and understandable name.
Houdini's `frontface` corresponds to "Shade Both Sides As Front" checkbox on UI which means logic should be reversed.
> Fix doublesided attribute of principled shader

- pxr/imaging/plugin/hdRpr/rifcpp/rifContext.cpp
Until there is no possibility to set up Metal interop with RIF, we have to use CPU RIF context
> Use CPU RIF context on macOS

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Projection matrix stored in HdCamera, whom delegate is Houdini's scene delegate, has been fixed and therefore can be used directly
> Refactor camera projection matrix calculation

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
If `houdini:interactive` render setting was not set, an interactive mode was mistakenly enabled due to incorrect fallback value
> Fix querying of "interactive mode" setting

- cmake/macros/Private.cmake
Currently, hdRpr binary on macOS has LC_RPATH in such form
`/Applications/Houdini/Houdini18.0.391/Frameworks/Houdini.framework/Versions/18.0/Libraries`.
This binds hdRpr.dylib to particular Houdini release.
With current changes, LC_RPATH will look like `@loader_path/.`
Why it will work? Because, right now, we place libraries required by hdRpr.dylib (RPR and RIF libraries) to the directory with USD libraries. USD libraries are responsible for plugin loading. In such a way, on the loading of hdRpr.dylib `@loader_path` will be substituted with the path to USD libraries.
> Make macOS hdRpr binary relocatable

- pxr/imaging/plugin/hdRpr/volume.cpp
Typical volume file consists of a density grid only, in such cases we set default color for each voxel.
When voxel color is black it will not be lit up with any existing light type.
> Set non-black color as default volume color

- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
For some reason, this [line](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/master/pxr/imaging/plugin/hdRpr/rpr/imageHelpers.cpp#L180) giving us GL_SRGB even for normal map .png images. So as normal maps are never sRGB encoded, we can safely force linear space usage for such textures
Related issue [FIR-1630](https://amdrender.atlassian.net/browse/FIR-1630)
> Force normal map texture linear space

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
While working with indoor scenes (like the attic and the esper room) I felt the need to apply tone mapping. So as RIF already has a bunch of tone mapping filter I tested a few of them and selected the most versatile one - [Linear Photographic Tone Mapping Filter](https://radeon-pro.github.io/RadeonProRenderDocs/rif/filters/linear_photographic_tone_mapping.html).
It's possible to add support for more tone mapping filters but I don't feel such need right now
> Embed tone mapping filter support

- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/basisCurves.h
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
* Support for curves of bezier basis
* Primitive support for catmullRom and spline bases by interpreting them as linear
* Support varying interpolation for widths
* Optimized a bit memory usage for linear curves - there is no need to [allocate memory](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/v1.2.2/pxr/imaging/plugin/hdRpr/basisCurves.cpp#L100) for dummy indices when there are no authored ones 
* Should we consider converting (in the plugin) catmullRom and spline bases to bezier or the current behavior is sufficient?
> BasisCurves improvements

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rendererPlugin.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
First of all, track whether we are rendering in batch mode or not and if so then do not resolve framebuffers on each iteration.
As the second optimization, introduce a progressive mode - whether we should update renderStats each sample or should we render at once as many samples as possible, depending on sampling mode: when uniform sampling mode is used, render all samples per one Render call; when adaptive sampling mode is used, render min samples first and then call Render for each sample progressively querying current active pixel count.
As for the naming convention, I followed husk because usdrecord has none of it. I'm going to add `renderMode` to usdrecord.
Here are some measurements: 12% performance gain (before:01:38.02-after:01:26.06) on basic0 test with adaptive sampling and 7% …
> Optimize batch rendering

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
I'm not exposing "Direct Illumination No Shadows" render mode because it does not work in core. See [FIR-1584](https://amdrender.atlassian.net/browse/FIR-1584)
Global Illumination
Direct Illumination
Wireframe
Ambient Occlusion
Diffuse
> Add render mode render setting

- pxr/imaging/plugin/hdRpr/distantLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.h
- pxr/imaging/plugin/hdRpr/light.cpp
- pxr/imaging/plugin/hdRpr/light.h
- pxr/imaging/plugin/hdRpr/renderParam.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Due to how is environment light creation/deletion implemented in RPR API we must remove default environment light before creating a new one
> Fix dome light visibility

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/aovDescriptor.cpp
- pxr/imaging/plugin/hdRpr/aovDescriptor.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
- pxr/imaging/plugin/hdRpr/rprApiFramebuffer.cpp
- pxr/imaging/plugin/hdRpr/rprApiFramebuffer.h
* Allow the user to bind any AOV supported by RPR
* Fix primId AOV: use `HdRprim::GetPrimId` as object id - effectively enables usdview's selection logic
* Workaround RPR's rule that sounds like "every AOV is multisampled" by resolving singlesampled AOV (any ID AOV, worldCoordinate, etc) only once. Related Issue [FIR-1681](https://amdrender.atlassian.net/browse/FIR-1681).
To be clear, by `singlesampled AOV` I mean AOV for which accumulation does not make any sense. The most outstanding example is `RPR_AOV_OBJECT_ID` - if a pixel on the edge of a few objects RPR will average IDs, this averaging will give you invalid ID.
Here are [AOVs](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/c7e153d7eed8e8b035562beb97bcd991aba0872a/pxr/imaging/plugin/hdRpr/aovDescriptor.cpp#L54-L …
> Improve AOV system

- pxr/imaging/plugin/hdRpr/material.cpp
- pxr/imaging/plugin/hdRpr/material.h
- pxr/imaging/plugin/hdRpr/materialAdapter.cpp
- pxr/imaging/plugin/hdRpr/materialAdapter.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
When mesh has few UV sets or it has non-standard (`st`) UV primvar name we must query the name of the needed UV primvar from bound material
> Query UV primvar name from bound material

- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/imageCache.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/util.cpp
- pxr/imaging/rprUsd/util.h
Before, hdRpr supported only `<UDIM>` tag in UDIM image paths.
These changes add support for SideFX syntax to define UDIM tiles - `%(UDIM)d`.
> Support SideFX-style UDIM tag

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
It was previously disabled because Northstar was always returning fully zeroed data despite the scene. It will be fixed in the next RPR SDK release
> Unlock alpha for northstar

- pxr/imaging/plugin/hdRpr/camera.cpp
- pxr/imaging/plugin/hdRpr/camera.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
Focal length and sensor size should be in millimeters
> Fix depth of field

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Houdini's Hydra makes some unnecessary changes with camera and viewport size on start. In short, something like this happens:
- **HdRenderIndex::SyncAll**
- **HdRenderPass::Execute** (the very first `rprContextRender` call happens here when RPR builds/compiles/syncs all its data)
- **Hydra releases camera and changes viewport size** (here is abort called when we are stoping the render thread) - that is how Houdini's Hydra used, we cannot do anything with it
- **HdRenderPass::Execute** (for some reason next `rprContextRender` is broken and renders nothing, most likely RPR was not thoroughly tested with such usage case - when the very first iteration is aborted)
Ideally, aborting the first sample should not be the problem. We would like to be able to abort it: to reduce response time, to …
> Fix undefined behavior on abort of the first rprContextRender

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Mutex double-lock happens on the creation of envLight when the scene has no lights, i.e. default light object is used.
We were using Release(defaultEnvLight) (locks mutex) from CreateEnvironmentLight (locks mutex too).
The easiest workaround here is to use Release(defaultEnvLight) that does not lock the mutex.
> Fix mutex double-lock on domeLight creation

- pxr/imaging/plugin/hdRpr/package/generatePackage.py
Without this check, CIS marks build as successful even in case of failed `cmake --build ...` command. Check [this build](https://rpr.cis.luxoft.com/blue/organizations/jenkins/RadeonProRenderUSDHoudiniPluginAuto/detail/develop/64) for example.
> Check cmake build return code

- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/points.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
RPR does not expose any way to control interpolation of values over faces, we can just interpret `varying` interpolation as `vertex` interpolation as they only differ in how exactly is data interpolated over the face (see [USD docs](https://graphics.pixar.com/usd/docs/api/class_usd_geom_mesh.html)):
* **varying**: One element for each point of the mesh; interpolation of point data is always linear.
* **vertex**: One element for each point of the mesh; interpolation of point data is applied according to the subdivisionScheme attribute.
As a bonus: I optimized a bit primvar descriptors querying - make sure we query them from the scene delegate only when required.
Added test here https://github.com/Radeon-Pro/USDTests/pull/9
> Support mesh primvars with `varying` interpolation

- .gitmodules
- CMakeLists.txt
- pxr/imaging/plugin/hdRpr/package/generatePackage.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/rprHoudini/CMakeLists.txt
- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp.in
* Weird error on Linux
* Use open-source implementation of std::filesystem in activateHoudiniPlugin utility:
CIS uses High Sierra but std::filesystem implemented only on Catalina+
* Package generation: if auto cleanup is enabled (default), make sure that the temporary build directory is removed to reset CMakeCache
> Fix CIS compilation errors

- pxr/imaging/plugin/hdRpr/light.cpp
Starting from RPR 1.35.5 Northstar takes the transform scale component into account on his analytic lights.
To reuse the existing code for geometry lights, we set the radius to 0.5 (size of geometry disk and sphere).
> Fix Northstar's analytic lights transform

- pxr/imaging/plugin/hdRpr/rprApi.cpp
We should resolve single sampled AOVs on the very first sample only.
The previous implementation was resolving single sampled AOVs only on the very first render update callback call when only part of the framebuffer is rendered.
Before:
After:
> Fix rendering of singlesampled AOV with Northstar

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Recent RPR core changed default LUT values for ID AOVs.
We need it to be exactly as it was before.
RPR 1.35.1
RPR 1.35.5
> Fix rendering of ID AOVs

- pxr/imaging/plugin/hdRpr/mesh.cpp
These changes enable selection in usdview for mesh instances:
https://youtu.be/8T865NAhzaQ
> Set mesh instance id to prototype mesh id

- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderBuffer.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/renderPass.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
* Houdini may reallocate (resync) HdRenderBuffer while it's mapped in another
thread (most likely for blitting to the viewport on the main thread).
When HdRenderBuffer is reallocated, we resize the underlying std::vector
and returned previously pointer from HdRenderBuffer::Map is invalidated.
github.com/sideeffects/HoudiniUsdBridge tells us that Karma's HdRenderBuffer
returns a pointer to the memory that is reallocated only on the next
HdRenderPass::_Execute in validateAOVs function.
So when Houdini makes Hydra reallocate all HdRenderBuffers it has no
actual effect. These changes in fact postponed until HdRenderPass::_Execute.
So we do the same - render buffer is reallocated in HdRprRenderPass::_Execute
via HdRprRenderBuffer::Commit.
* Allow the user to decide whether a particular AOV …
> Fix crash on AOV resize in Houdini and other improvements

- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
Depth AOV always had wrong values: on the very first render pass it was zeroed, after that depth values were always one frame in the past.
Such behavior is hardly noticeable in the IPR but a quite obvious when rendering from cmd-line.
This was caused by the wrong ordering of `rif::Filter::Update` calls.
`rif::Filter::Update` function attaches the filter to the context's command queue.
The remap filter was attached before the NDC filter.
> Fix depth AOV

- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp.in
Oleksandr Kupriyanchuk, the writer, reported that when json package description uses a Windows-style path, the plugin does not work. It works for me with both UNIX-style and Windows-style paths. So as the changes required to fix it are very straightforward I was not digging it up for the root cause of this behavior.
> Force UNIX path-style in Houdini package json

- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp.in
Atsushi noticed that package json was not flushed until he presses any key to [unpause](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/blob/fb0c15bc394ab3e15ad68de0649807e4d47e4144/pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp.in#L258). That's simply because `system(pause)` was called before std::fstream is released (where flushing happens).
> Flush package json before pausing a program

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/contextHelpers.cpp
It pollutes and blows up tracing play files. This leads to reduced readability.
So as SetAOVindexLookup makes sense only on the plugin side we can safely disable it when tracing is enabled.
> Disable SetAOVindexLookup when tracing is enabled

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
In RPR 2.01.7 RPR_CONTEXT_PREVIEW was implemented for Northstar.
It allows us to selectively exponentially downscale pathtracing resolution.
RPR_CONTEXT_PREVIEW gives a more pleasant interactive preview than resolves from the render update callback: https://youtu.be/eAtIU3PeLdE
Temporary fix for tracking if the render was aborted (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/commit/7f52846a214106d14b702a438024660f78e4f7e9) will be reverted when  RPRNEXT-401 is resolved.
> Update interactive preview rendering for Northstar

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/helpers.h
* Correctly query RPR_FRAMEBUFFER_LPE property
* Use aovBinding's name for LPE AOV output name
Despite https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/317 is not merged yet, LPE AOV export in .rpr should be valid
> Fix LPE AOV exporting in .rpr

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
Rename `Full` to `Full (Legacy)` and `RPR 2.0 (Beta)` to `Full`
> Make RPR2 render quality default

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/coreImage.cpp
- pxr/imaging/rprUsd/coreImage.h
- pxr/imaging/rprUsd/imageCache.cpp
- pxr/imaging/rprUsd/imageCache.h
- pxr/imaging/rprUsd/materialNodes/houdiniPrincipledShaderNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.h
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
This is mainly the support of OCIO on the Hydra level.
In Houdini, you can specify the OCIO config path and the rendering color space. But convenient handling of the color space of the textures is yet to be implemented, most likely it will be implemented as a separate VOP node.
Though it's possible to control texture color space through `sourceColorSpace` parameter on UsdUVTexture with help of the `Edit Properties` node. But that's not obvious for anyone who doesn't know about it.
> OCIO support

- cmake/defaults/Packages.cmake
System's Half lib was taking precedence over Half lib from Houdini because we were searching first for Half without sidefx specific suffix.
Resolves #384
> CMake: fix searching of Half library for Houdini 18.5

- pxr/imaging/plugin/rprHoudini/VOP_RPRMaterial.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.h
While we don't have a generic primvar reader node, we support only UV primvar.
And for non-materialX material graphs, we can specify the name of the UV primvar via the UsdPrimvarReader node.
These changes add an ability to select UV primvar when we use materialX node.
It was required for the materialX scene from David. Here are before and after:
> Add `UV Primvar Name` parameter to MaterialX node

- cmake/modules/FindHoudiniUSD.cmake
- cmake/modules/FindRif.cmake
- cmake/modules/FindRpr.cmake
- deps/CMakeLists.txt
There are few main changes:
* Instead of setting per-target `_GLIBCXX_USE_CXX11_ABI=0` definition, set it globally to make sure that all targets use it
* Fallback to CentOS7 libraries when the current Linux platform is unknown:
- CentOS7 libs links against older GLIBCXX than Ubuntu18 and so it's more universal
> Fix Ubuntu 20.04 build

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
Render Settings node UI is not up-to-date.
* Show adaptive sampling only for Legacy Full quality
* Hide interactive max ray depth for Low-High qualities
* Show alpha checkbox for all render qualities
> Update render settings UI

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
Previously, we were not able to distinguish 0 id pixels and void pixels (where no geometry present).
By offsetting the AOV index lookup by one we can achieve that void pixels will have -1 id.
Empty pixels now have a valid value (-1). It allows distinguishing empty pixels and pixels that contain id==0. For usdview, it enables deselection by pressing on empty space and avoids selection of the first object when selecting empty space.
Do offset each AOV index lookup by one, thus allowing us to get id 1 for the first element and 0 for empty space. By offsetting it back, we get 0 id for the first element and -1 for empty space.
> Improve ID AOVs

- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp.in
Starting from Houdini 18.5.402, it does not expand user-defined variables, so we do it manually.
Manually expand user-defined variables in the package JSON.
> Update Houdini's plugin activation utilitiy

- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.h
UsdPreviewSurface normal mapping looks wrong when used correctly.
Normal input now expects values in the correct range (accordingly to UsdPreviewSurface proposal) - tangent space [(-1,-1,-1).(1,1,1)].
Rescale input value from [-1;1] to [0;1] range required by RPR_MATERIAL_NODE_NORMAL_MAP
> Fix UsdPreviewSurface normal

- deps/CMakeLists.txt
- deps/rprMtlxLoader/rprMtlxLoader.cpp
- deps/rprMtlxLoader/rprMtlxLoader.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/coreImage.cpp
- pxr/imaging/rprUsd/coreImage.h
- pxr/imaging/rprUsd/imageCache.cpp
- pxr/imaging/rprUsd/imageCache.h
- pxr/imaging/rprUsd/materialNodes/materialNode.h
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
Do such conversions:
* single-channel (R) texture to RRR when it's used as RGB input
* RG texture into to RRRG when it's used RGBA input
* and others, see CoreImage.cpp:ConvertTexture
Fix unexpected behavior (from the artists point of view) when using single-channel grey textures, dual-channel (red-alpha), and others.
More artist-friendly texture appearance, e.g. single-channel greyscale jpegs.
* Evaluate the required number of channels for a texture:
* UsdUvTexture: depends on the connections in which this node participates
* MaterialX: depends on the type of image node
* Knowing the number of required channels and number of actual channels of a texture, convert accordingly
> Convert textures into a format required by the material graph

- pxr/imaging/rprUsd/materialNodes/materialNode.h
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.h
- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
To avoid saving .mtlx file to the disk when using `rpr_materialx_node`, the user might use `string` and `basePath` inputs to pass MaterialX through memory.
To allow using `rpr_materialx_node` without forcible saving .mtlx file to the disk.
Add a way to pass MaterialX as a string.
* Add `string` and `basePath` inputs to `rpr_materialx_node` that are hidden on UI
* When loading MaterialX via native MaterialX API use both string and file when available (effectively merge them)
> Add mtlx-string inputs for rpr_materialx_node

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
- pxr/imaging/plugin/hdRpr/python/commonSettings.py
- pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Support contour rendering with Northstar.
Added new render mode - **Contour**, and its render settings (linewidth of a particular edge detection feature and others). Added new geometry setting - **Ignore Contour**, that controls whether contour should be extracted for a mesh or not.
* Global Illumination mode
* Contour mode
* Refactored code generation scripts to extend its functionality:
* More generic way to define dynamic UI menus.
* It allows us to dynamically add Contour render mode entry depending on the current render quality:
* Add collapsible folders.
* It allows us to group contour settings into one collapsible folder
* Improved HdRprApiAov creation. Now we set the DirtyAOVRegistry flag when HdRprApiAov is released. Previously it was not required because HdRprApiAov could have …
> Expose contour rendering mode

- pxr/imaging/plugin/rprHoudini/CMakeLists.txt
- pxr/imaging/plugin/rprHoudini/LOP_RPRMaterialProperties.cpp
- pxr/imaging/plugin/rprHoudini/LOP_RPRMaterialProperties.h
- pxr/imaging/plugin/rprHoudini/plugin.cpp
- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/tokens.cpp
- pxr/imaging/rprUsd/tokens.h
To allow the user to control the material ID that is rendered on the corresponding AOV.
Added new LOP node (`RPR Material Properties`) for overriding material ID.
* New LOP node that sets required inputs on a material
* Query new inputs in material creation code
> Add a way to override material IDs

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/python/generateFiles.py
- pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
- pxr/imaging/plugin/hdRpr/python/generateLightSettingFiles.py
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
To speed up the build time.
Faster plugin building.
Reduce the number of python processes when generating files on the build. Instead, execute generation code from the main python process.
On my machine, it gives a 13% improvement - the time of full build reduced from 78 seconds to 68.
> Reduce the number of python processes when generating files on build

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
- pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
To allow the user to control the object ID that is rendered on the corresponding AOV.
Added `ID` parameter to the `Render Geometry Settings` LOP node.
Parse id from the constant primvars and if it's authored override `HdRprim::GetPrimId`.
> Add a way to override mesh ID

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
For a better user experience, we were preallocating denoise AOVs in advance to allow the user to enable/disable denoising without resetting AOVs at any time. For Northstar, creating additional denoise AOVs (albedo, normal) critically affects its performance. For Tahoe, it was only memory overhead, the performance penalty was miserable. 
* Highly reduce time to first pixel for Full (RPR 2.0) render quality when denoise is not enabled.
* Change denoise usage.
* Now when denoise is enabled/disabled we clear AOVs
* Add two settings to control denoise behavior (like in RPR Blender plugin):
* `Denoise Min Iteration` - the first iteration on which denoising should be applied.
* `Denoise Iteration Step` - denoise use frequency. To denoise on each iteration, set to 1.
* Create denoise AOVs lazily …
> Create denoise AOVs lazily

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Fix crash on resizing viewport when denoising enabled
None - changes that lead to this crash were not released yet.
Change the order of AOVs updates - at first, create all required AOVs (denoise AOVs in this case) and only then resize if viewport was changed.
> Fix crash on resizing viewport when denoising enabled

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Create and manage AOVs in the way contour render mode requires it.
None, changes were not released.
All contour AOVs (normal, primid, materialId) should always exist, even if RPR_CONTEXT_CONTOUR_USE_* is set to 0
> Fix AOV management in contour rendering mode

- pxr/imaging/plugin/rprHoudini/CMakeLists.txt
- pxr/imaging/plugin/rprHoudini/UsdRenderers.json
To improve UX. When the user changes such render qualities as renderQuality and renderDevice, we need to resync the scene because changing these settings requires RPR context recreation. Previously, the user had to do it manually through Houdini UI.
No more need to restart render manually when changing render quality.
Accordingly to this [new doc](https://www.sidefx.com/docs/hdk/_h_d_k__u_s_d_hydra.html#HDK_USDHydraConfiguration) we can put UsdRenderers.json config into HOUDINI_PATH to customize render delegate usage (see `restartrendersettings` key).
> Configure Houdini plugin for automatic renderer restart

- pxr/imaging/plugin/rprHoudini/LOP_RPRMaterialProperties.cpp
Some users still want to compile hdRpr with USD 19.11. https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/410 introduced changes that can't be compiled with USD 19.11 - it uses `UsdPrim::GetPrimTypeInfo` that was introduced only in USD 20.08.
None, changes that lead to this issue were not released.
> Fix compilation for USD 19.11

- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
Reported by Morgenrot Jp.
Though in hdRpr we don't support correctly displayColor due to the absence of primvar support, there is no reason to ignore displayColor with any interpolation except constant like it was before for meshes.
Use displayColor primvar with any interpolation (still limited to one color)
> Use displayColor with any interpolation

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/contextHelpers.cpp
- pxr/imaging/rprUsd/contextHelpers.h
Recent changes (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/379) lead to undesired behavior - RPR tracing had this line inside of it:
```
rprContextSetParameterByKey1u(context,RPR_CONTEXT_TRACING_ENABLED,(rpr_uint)1);  RPRTRACE_CHECK
```
It means that when you run the trace, the trace itself enables tracing.
So the purpose is to avoid leaking RPR_CONTEXT_TRACING_ENABLED into the trace.
None
> Fix RPR trace generation

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Since #413, color AOV is not created in advance.
From the other side, RPR refuses to render if color AOV is not created.
It's possible for Hydra to ignore color AOV.
For example, in usdview when depth AOV is selected, only depth AOV is bound.
That's why we must always create color AOV.
Fix errors on the call of `rprContextRender` when color AOV is not bound.
Fixed rendering when non-color AOV is enabled in usdview 20.08+.
Create color AOV when initing the RPR context.
> Fix rendering when color AOV is not bound

- pxr/imaging/plugin/rprHoudini/VOP_RPRMaterial.cpp
To fix crash on save of .hip.
Fixed crash on save of .hip.
Validate callback data before use.
> Fix crash on save of .hip

- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.h
To fix https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/433
Fixed UsdPreviewSurface displacement defined with a constant
Use the output of the displacement node instead of the displacement node itself as a displacement output of the UsdPreviewSurface node.
> Fix UsdPreviewSurface displacement defined with a constant

- pxr/imaging/plugin/hdRpr/mesh.cpp
Resolve https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/435
Non-refined subdivision surface visualized with smooth normals
At the same time, it's still possible to render subdivision surfaces with flat shading if needed by changing mesh display style.
Generate smooth normals for non-refined subdivision surface
> Generate smooth normals for non-refined subdivision surface

- pxr/imaging/plugin/hdRpr/baseRprim.h
- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/basisCurves.h
- pxr/imaging/plugin/hdRpr/camera.cpp
- pxr/imaging/plugin/hdRpr/camera.h
- pxr/imaging/plugin/hdRpr/distantLight.cpp
- pxr/imaging/plugin/hdRpr/instancer.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/points.cpp
- pxr/imaging/plugin/hdRpr/points.h
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/contextHelpers.cpp
- pxr/imaging/rprUsd/coreImage.cpp
- pxr/imaging/rprUsd/imageCache.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/util.cpp
- pxr/imaging/rprUsd/util.h
Update to USD 21.02
hdRpr is up to date with USD 21.02
Fixed such USD 21.02 updates:
* removed instancerId from HdInstancer and HdRprim constructors
* removed angle token from UsdLuxTokens
* replaced GLEW with their own GL API loader
* changed GlfUvTextureData format API
* added new camera framing API
* changed projection underlying type from TfToken to HdCamera::Projection
hdRpr is still compatible with USD down to 19.11.
> Update to USD 21.02

- cmake/modules/FindHoudiniUSD.cmake
For some reason, the Houdini Python3 installation on CIS contains both py2 and py3 includes. The easiest way to work around this by changing the order of checking for the python version.
> CIS Houdini python3 workaround

- pxr/imaging/plugin/hdRpr/baseRprim.h
- pxr/imaging/plugin/hdRpr/basisCurves.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/rprHoudini/LOP_RPRMaterialProperties.cpp
Fix crashes
* Fixed crash after updating material when it's assigned to the invisible mesh.
* Fixed crash when Houdini's graph is in an invalid state (missing file, etc) and "RPR Material Properties" node present.
* hardcode `_sharedData.visible=true`
`HdRprim::CanSkipDirtyBitPropagationAndSync` decides whether Rprim can be skipped from syncing. In short, when Rprim is invisible this function tells `HdRenderIndex::SyncAll` to skip the primitive. Ideally, that's what we want but not in the case of RPR. If the invisible Rprim has active material reference and the referenced material was changed we must resync the Rprim. As there is no way to change the behavior of `HdRprim::CanSkipDirtyBitPropagationAndSync` (it's not virtual) to not skip when the material was changed, we make our Rprim to …
> Fix crash on material update

- pxr/imaging/plugin/hdRpr/mesh.cpp
To support constant UV primvar on meshes.
Added support of UVs with constant interpolation.
> Support constant primvars on meshes

- pxr/imaging/plugin/hdRpr/rprApiAov.h
Fix invalid initialization of computed AOVs (mask id, depth).
None. This bug is from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/440 that was not released yet.
> Fix computed AOV initialization

- pxr/imaging/plugin/hdRpr/domeLight.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Request from RPRViewer's devs
Allow the user to override the environment light background with a custom color by setting `rpr:backgroundOverride` attribute on a dome light object.
> Expose environment light background override

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderBuffer.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Optimize final rendering in RPRViewer.
* Speed up rendering via husk in case of multiple render products
* Allow dynamic change of session type (batch/interactive)
Previously, it was possible to enter batch session only at the time of render delegate initialization.
These changes move the handling of the corresponding render setting to HdRprConfig thus allowing interactive change of the session type. Also, fixed the case when there are few AOVs to resolve - previously each resolve call would block separately.
As a side effect, it was required to rename renderMode render setting that controlled rpr_render_mode to coreRenderMode to avoid conflicts with Houdini's renderMode render settings that control session type.
> Allow dynamic change of session type

- pxr/imaging/plugin/hdRpr/rprApi.cpp
PR created to have valid render stats, without these changes progress doesn't updated for first iterations
Valid render stats percent field
Active pixels count doesn't updated when numSamples < minSamples
None
> Adaptive sampling fix

- pxr/imaging/rprUsd/materialNodes/mtlxFiles/Shaders/rpr_blend.mtlx
- pxr/imaging/rprUsd/materialNodes/mtlxFiles/Shaders/rpr_orennayar.mtlx
- pxr/imaging/rprUsd/materialNodes/mtlxFiles/Shaders/rpr_refraction.mtlx
There are several typos with cyrillic characters in some .mtlx files. They were found during importing RPR MaterialX nodes into Blender USD plugin.
Fixed typos with cyrillic characters in some .mtlx files
> Fixed cyrillic typos in some .mtlx files.

- README.md
- pxr/imaging/plugin/rprHoudini/CMakeLists.txt
- pxr/imaging/plugin/rprHoudini/MatLib_INSTALL.md
- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp
- pxr/imaging/plugin/rprHoudini/activateMatlibPlugin.cpp
- pxr/imaging/plugin/rprHoudini/houdiniPluginActivator.cpp.in
- pxr/imaging/plugin/rprHoudini/scripts/python/houRpr/materialLibrary.py
Resolve #453
Fixed crash on macOS on first use of the RPR Material Library.
The exact reason of the crash is not clear to me. I localized it to the usage of HTML in QMessageBox that displayed installation steps.
So to minimize HTML usage here I reworked the installation process a bit.
> Fix crash on macOS when using RPR Material Library and simplify its installation

- pxr/imaging/plugin/hdRpr/rprApi.cpp
To improve .rpr export
.rpr export now exports USD's depth AOV as RPR_AOV_DEPTH.
Instead of skipping ndcDepth AOV, map it to the linear depth instead (RPR_AOV_DEPTH)
> .rpr export: export depth AOV as RPR_AOV_DEPTH

- pxr/imaging/plugin/hdRpr/light.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/coreImage.cpp
- pxr/imaging/rprUsd/coreImage.h
- pxr/imaging/rprUsd/imageCache.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/util.cpp
- pxr/imaging/rprUsd/util.h
To support USD 21.05 builds.
Added support of USD 21.05.
* Replace GlfUvTextureData usage with RprUsdTextureData that hides USD version differences:
- GlfUvTextureData is removed in 21.05 and fully replaced with HioImage
* Workaround UsdLuxTokens changes
> Update to USD 21.05

- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/materialNodes/rpr/arithmeticNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/catcherNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/combineShadersNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/displaceNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/nodeInfo.h
- pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp
Adds a toon shader node for users
Users can create toon shader looks. 
Currently, there is no way to easily implement dynamic UI like in the blender - such functionality is simply not available and should be implemented on our own. So this PR adds an analog of the toon shader from the blender in an advanced mode with all parameters always visible. I've added dynamic UI functionality to my TODO list but obviously it requires time, of which I don't have enough right now.
> Add toon shader node

- pxr/imaging/plugin/hdRpr/mesh.cpp
In some cases we have mismatch between hdrpr mesh id and usd prim id, this fix should resolve issue
Fixed prim id update logic
Set prim id in case DirtyPrimId
None
> Update prim id on DirtyPrimId

- pxr/imaging/plugin/hdRpr/light.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
After updating USD to 21.05 release there are following errors:
1. Light position: `Error in 'pxrInternal_v0_21__pxrReserved__::VtValue::_FailGet' at line 565 in file D:\amd-gpuopen\BlenderUSDHydraAddon\deps\USD\pxr\base\vt\value.cpp : 'Attempted to get value of type 'GfMatrix4d' from empty VtValue.'`
2. Camera: `[RPR ERROR] Failed to set camera focus distance -- invalid parameter in UpdateCamera at line 1809 of D:\amd-gpuopen\BlenderUSDHydraAddon\deps\HdRPR\pxr\imaging\plugin\hdRpr\rprApi.cpp(7adc67f)`
Fixed light positioning and log error with camera focus distance for USD 21.05.
- fixed getting light transform
- added check for camera focus distance
Probably we need more checks here to support older USD versions. @hshakula ?
> Made adjustments due to USD 21.05 changes:

- .gitmodules
- cmake/defaults/Packages.cmake
- deps/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/material.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
- pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/rprHoudini/LOP_RPRMaterialProperties.cpp
- pxr/imaging/rprUsd/helpers.h
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
- pxr/imaging/rprUsd/tokens.h
To improve cryptomatte integration
* Added a way to configure cryptomatte names for materials and meshes.
* Added cryptomatte export
Such custom implementation of cryptomatte export is required because there is no other way to export valid cryptomatte files from Houdini.
> Extend cryptomatte support

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
- pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Adds support of deformation motion blur
* Added support of deformation motion blur in the Full quality.
* New geometry render setting introduced - "Geometry Time Samples". The number of sub-frame samples to compute when rendering deformation motion blur over the shutter open time. The default is 1 (sample only at the start of the shutter time), giving no deformation blur by default. If you want rapidly deforming geometry to blur properly, you must increase this value to 2 or more. Note that this value is limited by the number of sub-samples available in the USD stage being rendered. Set to 0 to get all sub-samples available in the USD stage.
* Use `HdSceneDelegate::SamplePrimvar` instead of `HdSceneDelegate::Get` to query the required amount of time samples from the scene delegate.
* Add …
> Add support of deformation motion blur

- deps/CMakeLists.txt
Centos builds cannot be created due to compilation errors.
> Fix compilation error

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/plugin/hdRpr/volume.cpp
To resolve #495.
Single-colored VDB volume can now be achieved by using volume's `gain` parameter.
Test project:  [RPR_smoke_color.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6874606/RPR_smoke_color.zip)
* make `bias` and `gain` parameters of `GfVec3f` type.
> Add an easy way to make single-colored VDB volume

- cmake/defaults/Packages.cmake
To fix compilation with Houdini 18.5.596+ on macOS
--
Patch `HoudiniConfigVersion.cmake` that is shipped with the Houdini.
> Fix compilation with Houdini 18.5.596+ on macOS

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/usdviewMenu/rpr.py
- pxr/imaging/plugin/rprHoudini/CMakeLists.txt
- pxr/imaging/plugin/rprHoudini/scripts/python/houRpr/cache.py
- pxr/imaging/plugin/rprHoudini/scripts/python/houRpr/devices.py
- pxr/imaging/plugin/rprHoudini/scripts/python/houRpr/materialLibrary.py
- pxr/imaging/plugin/rprHoudini/ui/MainMenuCommon.xml
- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/__init__.py
- pxr/imaging/rprUsd/config.cpp
- pxr/imaging/rprUsd/config.h
- pxr/imaging/rprUsd/contextHelpers.cpp
- pxr/imaging/rprUsd/contextHelpers.h
- pxr/imaging/rprUsd/contextMetadata.h
- pxr/imaging/rprUsd/devicesConfiguration.py
- pxr/imaging/rprUsd/module.cpp
- pxr/imaging/rprUsd/wrapConfig.cpp
- pxr/imaging/rprUsd/wrapContextHelpers.cpp
To improve render device selection.
* Added a new GUI for render device selection. It can be found under the main menu in RPR->Render Devices.
* Removed the renderDevice render setting.
The device configuration is tied to the current hardware. By default, only one GPU is used, if available, otherwise all CPU threads are used. It's now possible to select any device combination. Render devices are configured per plugin (this is motivated by the fact that each particular plugin might behave differently for a different combination of hardware, e.g. Tahoe might be slower with CPU+GPU rendering while Northstar not, Hybrid does not support CPU rendering at all).
* Render device configuration GUI is implemented with PyQt.
* Render device configuration is saved under a separate cache folder as a …
> Render device selection

- pxr/imaging/plugin/hdRpr/distantLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.cpp
DistantLight and DomeLight doesn't work after updating USD to 21.05.
`Error in 'pxrInternal_v0_21__pxrReserved__::VtValue::_FailGet' at line 565 in file D:\amd-gpuopen\BlenderUSDHydraAddon\deps\USD\pxr\base\vt\value.cpp : 'Attempted to get value of type 'GfMatrix4d' from empty VtValue.'`
DistantLight and DomeLight now works.
Fixed getting light transform
Same fixes as here https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/pull/476
> DistantLight and DomeLight fix

- pxr/imaging/plugin/hdRpr/distantLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.cpp
PURPOSE
DistantLight and DomeLight doesn't work after updating USD to 21.05.
Error in 'pxrInternal_v0_21__pxrReserved__::VtValue::_FailGet' at line 565 in file D:\amd-gpuopen\BlenderUSDHydraAddon\deps\USD\pxr\base\vt\value.cpp : 'Attempted to get value of type 'GfMatrix4d' from empty VtValue.'
EFFECT OF CHANGE
DistantLight and DomeLight now works.
TECHNICAL STEPS
Fixed getting light transform
NOTES FOR REVIEWERS
Same fixes as here #476
> Fix transform sync of DistantLight and DomeLight

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
To improve adaptive sampling performance with RPR2 in batch mode
Improved performance of batch rendering when adaptive sampling enabled for the Full quality.
Disable `RPR_CONTEXT_ACTIVE_PIXEL_COUNT` check for northstar.
> Improve adaptive sampling performance with RPR2 in batch mode

- pxr/imaging/plugin/hdRpr/rprApi.cpp
To improve the camera feature set. To resolve #181.
The camera's aperture offset is now supported.
Copy implementation from the blender addon.
I've tested it in Houdini by comparing it to `Houdini GL` delegate renders.
> Add support for aperture offset

- cmake/defaults/Packages.cmake
- cmake/defaults/msvcdefaults.cmake
- cmake/modules/FindHoudiniUSD.cmake
- cmake/modules/FindRpr.cmake
- deps/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/renderDelegate.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/rprHoudini/VOP_RPRMaterial.cpp
- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/contextHelpers.cpp
- pxr/imaging/rprUsd/contextMetadata.h
- pxr/imaging/rprUsd/materialNodes/materialNode.h
- pxr/imaging/rprUsd/materialNodes/rpr/materialXNode.cpp
- pxr/imaging/rprUsd/materialNodes/rprApiMtlxNode.cpp
- pxr/imaging/rprUsd/materialNodes/rprApiMtlxNode.h
- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
To support MaterialX via UsdShade.
Added support of MaterialX defined via UsdShade network.
* Disable the custom mtlx loader if the target USD has materialX
* Add HybridPro RPR plugin
* Use hdMtlx to convert UsdShade network to Materialx::Document
> UsdShade materialX support

- pxr/imaging/rprUsd/config.cpp
PURPOSE
Added method to create all necessary parent's directories.
The reason is CreateDirectory() throws an exception if any parent's folder does not exist
> Create parent dirs for shader cache folder

- pxr/imaging/plugin/hdRpr/instancer.cpp
- pxr/imaging/plugin/hdRpr/instancer.h
- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
After migrate to USD 21.11 we've got invalid instancer logic. They weren't work if composed into nested structures
Fixed nested instancers transforms
- Called _SyncInstancerAndParents on instancer, which calls Instancer::Sync() under hood 
- Implemented virtual Sync() method for HdRprInstancer. Logic was taken from HdStInstancer
- Removed unused code
None
> Nested instancer fix

- pxr/imaging/plugin/rprHoudini/VOP_RPRMaterial.cpp
- pxr/imaging/plugin/rprHoudini/VOP_RPRMaterial.h
- pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp
- pxr/imaging/rprUsd/materialRegistry.h
To improve UX when using RPR Toon node.
RPR Toon node dynamically hides/shows its parameters.
> Dynamically hide unused parameters of RPR Toon node

- pxr/imaging/plugin/hdRpr/primvarUtil.h
To make attribute getting work across required USD versions (20.11, H18.5, H19.0).
None.
> Fix attribute getting

- pxr/imaging/rprUsd/materialNodes/materialNode.h
- pxr/imaging/rprUsd/materialNodes/usdNode.cpp
- pxr/imaging/rprUsd/materialNodes/usdNode.h
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
When continuous parameter change triggers full material rebuild, render might be aborted before resources are committed, thus texture load result is discarded. With these changes, we avoid loading texture if it's not needed anymore and avoid potential crashes when calling texture callback for the already released material node.
Fix random crashes on continuous scene changes (e.g. dragging transform or material parameters).
Instead of storing texture load data as is, store a weak reference to it. Material that enqueues texture load stores strong reference. Thus if the material is released before a texture load request has been processed, it will be invalidated.
> Update texture loading

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
Do not show prototype if an instancer has no instances
Prototype mesh is no more shown when an instancer has no instances.
> Do not show prototype if instancer has no instances

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/schema.usda
Add camera render mode render setting
A new render setting is added - "Camera Mode". More info about the modes [here](https://radeon-pro.github.io/RadeonProRenderDocs/en/sdk/info_setting_types/rpr_camera_mode.html?highlight=camera%20mode). The "perspective" and "orthographic" mode is controlled by USD's camera. Other modes are exposed as overrides. Cubemap camera modes are not available in the Full quality (not supported yet).
> Add camera mode render setting

- pxr/imaging/plugin/hdRpr/light.cpp
- pxr/imaging/plugin/hdRpr/python/generateLightSettingFiles.py
- pxr/imaging/rprUsd/schema.usda
Fix light visibility flags
Fixed light visibility flags in the latest Houdini.
Added light visibility flags to the schema. Updated the way visibility flags are queried in HdRprLight::Sync.
A Houdini project showcasing the fix can be downloaded [here ](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/8550426/lightVisibilityTest.zip)
Make sure to read this:
Expected render:
> Fix light visibility flags

- pxr/imaging/rprUsd/hdMtlxFixed.cpp
Currently files that have relative paths to textures are not processed correctly: RadeonProRenderUSD can not find these textures.
Files that have relative paths to textures are now processed correctly.
SdfAssetPath::GetReslvedPath() returns absolute path to the texture file, thus materialX file with absolute paths is constructed.
> Fix processing relative path to the textures

- cmake/modules/FindOpenEXR.cmake
The problem is that the CIS machine has EXR library installed in /usr and CMake gives it priority over Houdini's libraries by default. By specifying `NO_DEFAULT_PATH,NO_SYSTEM_ENVIRONMENT_PATH` we can disable this behavior
> Fix compilation error on Ubuntu CIS machine

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/schema.usda
Houdini USD use "stageMetersPerUnit" token name to provide unit size data. We need to use token with same name. https://www.sidefx.com/docs/hdk/_h_d_k__u_s_d_hydra.html#HDK_USDHydraCustomSettings
Now scene unit token is renamed to be same with Houdini. Also, token added to hdRPR parameters schema.
> Scene units token rename

- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/material.cpp
Fix for https://amdrender.atlassian.net/browse/RPRUS-107
Test crashes when rprShapeSetSubdivisionFactor is used on mesh without normals.
The solution is simply avoid rprShapeSetSubdivisionFactor call when mash has no normals
> autotests fix

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Vertex color primvars are not supported in HdRPR
Now HdRPR can support "displayColor" primvars.
1) This feature works only with Northstar renderer.
2) Instance interpolation is not supported by RPR. Now it's being ignored
> Color primvars

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Delegate produces incorrect depth AOV if scene unit size is not equal 1
Now depth AOV is correct with all unit sizes
Depth image is being calculated by RIF using world coordinates and camera view matrix. This PR applies scene unit size to view matrix.
> Depth AOV fix

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.cpp
- pxr/imaging/plugin/hdRpr/primvarUtil.h
See description.
If the mesh doesn't have a primvar named "st" then it will find the next primvar with the texture coordinate [roll](https://graphics.pixar.com/usd/dev/api/_usd__page__datatypes.html#Usd_Roles).
See 'Effect of Change'
The primary downside to this approach is if the mesh has multiple texcoords it will pick just the first one, which may not be what the materialX needs.  But since hdRPR currently doesn't support multiple texcoords I think this is acceptable.
> Allow materialX to read texture coordinates that are not named "st"

- pxr/imaging/rprUsd/materialNodes/rprApiMtlxNode.cpp
- pxr/imaging/rprUsd/materialRegistry.cpp
- pxr/imaging/rprUsd/materialRegistry.h
MaterialX sync process takes a lot of time when scene has mane MaterialX nodes
Now sync speed is increased on about 40%
In previous version common libraries are being loaded for each node. In this PR library loading moved to common class. Also now rpr node can be created from matX string without a temp file
> MaterialX performance improvement

- pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/rprUsd/devicesConfiguration.py
Legacy Tahoe plugin is in render settings
Now Tahoe has been removed from settings
This PR makes Tahoe fully unavailable! Other Tahoe code will be deleted later
> remove tahoe from render settings

- pxr/imaging/plugin/hdRpr/aovDescriptor.cpp
- pxr/imaging/plugin/hdRpr/mesh.cpp
hdRPR does not support instanceId AOV
Now instanceId AOV support is added
Now we use RPR_AOV_OBJECT_ID as instanceID and RPR_AOV_MESH_ID as primId
> instanceId aov

- pxr/imaging/plugin/hdRpr/rprApi.cpp
After adding instanceId AOV contour rendering in production mode is brocken
Now coutour rendering works correctly
After adding instanceId AOV RPR_AOV_OBJECT_ID in Hydra PrimId AOV had been replaced to RPR_AOV_MESH_ID. But contour mode requires OBJECT_ID. In this PR instanceId, which contains RPR_AOV_OBJECT_ID, has been set as required for contour rendering
> Contour render fix

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/rprUsd/contextHelpers.cpp
- pxr/imaging/rprUsd/contextHelpers.h
- pxr/imaging/rprUsd/contextMetadata.h
This PR adds some render info and render statistics information to be available outside hdRPR via GetRenderStats function.
- GPU names which were actually used for context creation.
-  CPU thread count.
- First iteration render time (which is approximation for cache creation time).
Plugin which uses hdRPR can now get some render data and statistics from it.
I used GetRenderStats() function of hydra render delegate interface to provide necessary information for the plugins which use hdRPR.
> Add some render statistics

- pxr/imaging/rprUsd/materialNodes/rprApiMtlxNode.cpp
HybridPro has rendering artefacts with MaterialX 
Now hybrid pro can work correctly 
Loading MaterialX file using temp file had been added. It will be removed after fix on HybridPro side
> HybridPro MaterialX temp fix

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/aovDescriptor.cpp
- pxr/imaging/plugin/hdRpr/aovDescriptor.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.cpp
- pxr/imaging/plugin/hdRpr/rprApiAov.h
Customers need to get shadow catcher image with transparent background
Added new AOV (scTransparentBackground) which can display schadow catcher composite image with transparent background
We make composition using color, opacity and shadow catcher AOVs. Composition is on CPU to avoid using RIF
> Shadow catcher cpu combine

- pxr/imaging/plugin/hdRpr/domeLight.cpp
HdRPR incorrectly process dome light rotation transforms
This PR can fix issue with dome light rotations
There was wrong order of transform matrix multiplication. Now it's fixed
> Dome light transform fix

- cmake/modules/FindOpenEXR.cmake
Update cmake file to fix plugin build for viewer
viewer build doesn't work correctly when NO_DEFAULT_PATH and NO_SYSTEM_ENVIRONMENT_PATH are used.
As they used for linux build, they can be defined as linux only.
> cmake viewer fix

- pxr/imaging/plugin/hdRpr/light.cpp
- pxr/imaging/rprUsd/CMakeLists.txt
- pxr/imaging/rprUsd/lightRegistry.cpp
- pxr/imaging/rprUsd/lightRegistry.h
- pxr/imaging/rprUsd/materialNodes/rpr/toonNode.cpp
Implemented flag to use mid color as albedo
Implemented toon light link setting
Resolves: https://amdrender.atlassian.net/browse/RPRHOUD-35
(Transparency and 5 colors setting are already implemented)
AlbedoMode setting, mid color used for albedo when selected
LinkedLight setting, when entered light path, it used for shader
To have a connection between light objects and their path in the scene I dad to add a LightRegistry singleton class. HdRprLight updates it when light is synced/deleted. When a path to the light becomes updated in the toon shader it requests a pointer to the light by its path from the LightRegistry. It also passes a callback, wich updates toon closure node when the light changes.
> Additional settings for toon shader

- pxr/imaging/plugin/hdRpr/light.cpp
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-39
IES profile direction used Y-direction, changed to Z-direction by prim rotation
> IES light direction adjustment

- pxr/imaging/plugin/hdRpr/mesh.cpp
WHAT:
There was a typo in vertex color assignment for geomsubset case. This is just a fix for typo
> Make a fix for vertex color in geomsubset

- pxr/imaging/plugin/rprHoudini/activateHoudiniPlugin.cpp
- pxr/imaging/plugin/rprHoudini/houdiniPluginActivator.cpp.in
Plugin package for Houdini does not contain version info
Now version info added to package metadata
Information is being copied from version file during installation
> Add version info to package

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Implements correct tiling for orthographic camera
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-32
For an orthographic camera, it moves the camera to a distance based on the aperture to place it in the middle of the rendered tile. 
Also, camera motion should be disabled for this temporal shift.
> Orthographic camera tiling implementation

- pxr/imaging/plugin/hdRpr/rprApi.cpp
rprContextSetAOVindicesLookup function is faster than rprContextSetAOVindexLookup
Now rprContextSetAOVindexLookup is replaced with rprContextSetAOVindicesLookup. We can use single call to set up all index colors.
> Replace multiple calls to AOVIndicesLookup

- pxr/imaging/plugin/hdRpr/rendererPlugin.h
IsSupported() function was removed in USD 23.02
removed override specifier to avoid build error
> usdview build quickfix

- pxr/imaging/plugin/hdRpr/mesh.cpp
WHAT:
In case if no vertex data was read HybridPro will create a mesh anyways which will lead to crash subsequently.
WHY: 
We need to avoid the crash
HOW:
One additional check added to prevent plugin from crash
> Fix for the case of empty mesh (no vertices) in HybridPro mode

- pxr/imaging/plugin/hdRpr/CMakeLists.txt
- pxr/imaging/plugin/hdRpr/domeLight.cpp
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-41
As RPR does not support .rat files, this PR converts them to .exr and replaces the path passed to CreateEnvironmentLight()
The converted file is placed in the directory of the original .rat file, or, if it fails, in case of, for instance, write protection, into subdir in HDRPR_CACHE_PATH_OVERRIDE.
> rat files conversion

- pxr/imaging/plugin/hdRpr/rprApi.cpp
Contour render mode is not supported on CPU, Texindex mode doesn't work properly on CPU and GPU simultaneously. This PR disables this mode if selected and shows a warning.
> render mode warnings

- pxr/imaging/plugin/hdRpr/distantLight.cpp
- pxr/imaging/plugin/hdRpr/domeLight.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
added missing support for distant and environment lights
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-50
> toon shader linking with distant and environment lights

- pxr/imaging/plugin/hdRpr/rendererPlugin.h
- pxr/imaging/rprUsd/materialNodes/rprApiMtlxNode.cpp
In latest Hybrid Pro release loading materialx as string was fixed
This PR enables loading materialX as string without temp files
> Restore mtlx string loading

- cmake/defaults/Packages.cmake
IMath lib is required for hdRPR built against Maya 2024.
So we need just add it to cmake scripts
> IMath is required for bulding hdRPR against USD in maya 2024

- pxr/imaging/rprUsd/hdMtlxFixed.cpp
I encountered a crash on some scenes inside hdRPR. Its related to how materialx nodes gets processed.
I added a nullptr check to avoid a crash.
> MaterialX crash fix

- pxr/imaging/plugin/hdRpr/renderDelegate.cpp
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
Resolves: https://amdrender.atlassian.net/browse/RPRUS-158
Cache creation time is considered as the first render iteration time when the cache does not exist on renderer initialization. The iteration time is negligible in this case.
Sync time is considered as the time between the first call of sync and the renderer start.
> sync and cache time

- pxr/imaging/rprUsd/materialHelpers.h
Resolves https://amdrender.atlassian.net/browse/RPRUS-164
The emission mode property setting requires 1 for single and 2 for double-sided mode; the default behavior for comboboxes/enums is to use an integer for each option starting from 0. Thus, for some inputs, the value must be tuned.
> emission mode fix

- pxr/imaging/plugin/hdRpr/domeLight.cpp
Background color override fix for plugin other than Houdini
> Fix for Bg Color Override for plugins other than Houdini

- pxr/imaging/plugin/hdRpr/mesh.cpp
Removed condition that prevented normals initialization when the subdivision is active. That was a very strange action - subdivision cannot work correctly without normals.
> normals initialization for subdivision fix

- pxr/imaging/plugin/hdRpr/aovDescriptor.cpp
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-98
Cancels changes made in aovDescriptor, that lead to a failure for some reason. I'll investigate the cause later.
> render vars issue fix

- pxr/imaging/rprUsd/materialMappings.h
- pxr/imaging/rprUsd/materialNodes/mtlxFiles/Shaders/rpr_uber.mtlx
- pxr/imaging/rprUsd/materialNodes/rpr/baseNode.cpp
- pxr/imaging/rprUsd/materialNodes/rpr/baseNode.h
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-66
The intensity implementation is that the emission color should be multiplied by the intensity value (that's how it works in Blender plugin
To get this, BaseNode is extended with a class for the Uber node that adds an extra multiply node before the actual emission color node and redirects Uber's emission color and intensity inputs to this node.
> uber emission color intensity

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/renderParam.cpp
- pxr/imaging/plugin/hdRpr/renderParam.h
- pxr/imaging/plugin/hdRpr/renderPass.cpp
Restart render thread automatically after manipulations with HdRprApi
RprApiSafeWrapper is created when RprApi is requested for editing. It stops the render thread and resumes it when the editing is finished. The change takes into account that RprApi can be requested simultaneously from multiple threads, and restarts the render thread only when the last instance of RprApiSafeWrapper is destroyed.
This change fixes the problem of the render thread not restarting if no changes are made.
> Restart render thread automatically after manipulations with HdRprApi

- pxr/imaging/rprUsd/contextHelpers.cpp
Some trace files are being placed in current working directory. not in specified by environment variable
Now all files are placed in specified tracing directory
There was incorrect order of Core API calls. We should firstly specify tracing dir and after that enable tracing
> Fix issue with tracing directory

- pxr/imaging/plugin/rprHoudini/houdiniPluginActivator.cpp.in
1. on windows fixed path encoding issue
2. on macos added possible alternative path (Library alias)
> activator path encoding fix + alternative path for MAC

- pxr/imaging/rprUsd/hdMtlxFixed.cpp
After merging PR 703 there was a problem with some materials in HybridPro
For now materialX materials can be rendered with HybridPro without any issues
> Fix materialX problems from PR 703

- pxr/imaging/rprUsd/schema.usda
Schema contains descriptions for RIF upscaling and denoising, which were removed in PR #704
This PR removes outdated parameters from USD schema
> Remove RIF denoising and upscaling from schema

- pxr/imaging/plugin/hdRpr/mesh.cpp
- pxr/imaging/plugin/hdRpr/mesh.h
- pxr/imaging/plugin/hdRpr/rprApi.cpp
- pxr/imaging/plugin/hdRpr/rprApi.h
- pxr/imaging/rprUsd/materialMappings.cpp
- pxr/imaging/rprUsd/materialMappings.h
- pxr/imaging/rprUsd/materialNodes/mtlxFiles/CMakeLists.txt
- pxr/imaging/rprUsd/materialNodes/mtlxFiles/Utilities/rpr_primvar_lookup.mtlx
Resolves https://amdrender.atlassian.net/browse/RPRHOUD-43
Added support for displayOpacity in meshes, and lookup node to control color/opacity primvars
to use color/alpha vertex data, rpr_primvar_lookup node is implemented.
> Vertex alpha

- CMakeLists.txt
- README.md
- cmake/modules/FindHoudiniUSD.cmake
- pxr/imaging/plugin/hdRpr/domeLight.cpp
This PR fixes compile issues that occur during build with version 20 of the Houdini engine. Additionally, a small note about Python version with HFS environment variable was put to make it easier for people to adjust to the build environment.
Makes it possible to use the plugin with version 20.
In domeLight.cpp, a compile-time check occurs with `HDK_API_VERSION >= 20000000` to choose the correct type. This pattern is also visible in VOP_RPRMaterial.(h|cpp), where HDK_API_VERSION helps to distinguish. But in case the plugin source does not care about version compatibility, I think this code can be made more concise by not checking for version.
The build was confirmed working with an Indie installation of Houdini version 20.
Please let me know if there's a documented minimum supported …
> Update Houdini integration for version 20 and elaborate README

- .gitignore
It is convenient to have multiple top-level build directories distinguished by suffix, like `build-20`, `build-19`, etc. for developer experience
> Gitignore alternative build directories
